
import java.awt.Color;
import java.awt.Graphics;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class LesBilles extends javax.swing.JFrame {
    private Bille b1;
    private Bille b2;
    private int sel; //Bille selectionnée

    /**
     * Creates new form LesBilles
     */
    public LesBilles() {
        initComponents();
        this.b1 = new Bille();
        this.b2 = new Bille(100,100,30);
        this.b2.setCouleur(Color.blue);
        this.sel = 1;
    }
    @Override
    public void paint(Graphics g){
        super.paint(g);
        this.b1.dessineBille(PanDessin);
        this.b2.dessineBille(PanDessin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        BHaut = new javax.swing.JButton();
        BGauche = new javax.swing.JButton();
        BDroit = new javax.swing.JButton();
        BBas = new javax.swing.JButton();
        BBille = new javax.swing.JButton();
        PanDessin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitre.setText("Déplace les billes en cliquant dans le panneau ou avec les boutons !");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
            .addGroup(PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTitreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTitreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PDroit.setLayout(new java.awt.GridLayout(5, 1));

        BHaut.setText("Haut");
        BHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHautActionPerformed(evt);
            }
        });
        PDroit.add(BHaut);

        BGauche.setText("Gauche");
        BGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGaucheActionPerformed(evt);
            }
        });
        PDroit.add(BGauche);

        BDroit.setText("Droit");
        BDroit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDroitActionPerformed(evt);
            }
        });
        PDroit.add(BDroit);

        BBas.setText("Bas");
        BBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBasActionPerformed(evt);
            }
        });
        PDroit.add(BBas);

        BBille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBilleActionPerformed(evt);
            }
        });
        PDroit.add(BBille);

        getContentPane().add(PDroit, java.awt.BorderLayout.LINE_END);

        PanDessin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanDessinMouseClicked(evt);
            }
        });
        PanDessin.setLayout(new java.awt.GridLayout(1, 1));
        getContentPane().add(PanDessin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHautActionPerformed
        // TODO add your handling code here:
        if(this.sel == 1)
            this.b1.deplaceBille(0, -10);
        else
            this.b2.deplaceBille(0, -10);
        this.repaint();
            
    }//GEN-LAST:event_BHautActionPerformed

    private void BGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGaucheActionPerformed
        // TODO add your handling code here:
         if(this.sel == 1)
            this.b1.deplaceBille(-10, 0);
        else
            this.b2.deplaceBille(-10, 0);
        this.repaint();
            
    }//GEN-LAST:event_BGaucheActionPerformed

    private void BDroitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDroitActionPerformed
        // TODO add your handling code here:
         if(this.sel == 1)
            this.b1.deplaceBille(10, 0);
        else
            this.b2.deplaceBille(10, 0);
        this.repaint();
            
    }//GEN-LAST:event_BDroitActionPerformed

    private void BBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBasActionPerformed
        // TODO add your handling code here:
         if(this.sel == 1)
            this.b1.deplaceBille(0, 10);
        else
            this.b2.deplaceBille(0, 10);
        this.repaint();
            
    }//GEN-LAST:event_BBasActionPerformed

    private void BBilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBilleActionPerformed
        // TODO add your handling code here:
        if(this.sel == 1)
        {
            this.sel = 2;
            BBille.setForeground(this.b2.getCouleur());
            BBille.setText("Bille 2");   
        }
        else
        {
            this.sel = 1;
            BBille.setForeground(this.b1.getCouleur());
            BBille.setText("Bille 1");      
        }
    }//GEN-LAST:event_BBilleActionPerformed

    private void PanDessinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanDessinMouseClicked
        // TODO add your handling code here:
        int mx = evt.getX();
        int my = evt.getY();
        if(this.sel == 1){
            this.b1.setPosX(mx);
            this.b1.setPosY(my);
        }else
        {
          this.b2.setPosX(mx);
          this.b2.setPosY(my);   
        }
        this.repaint();
    }//GEN-LAST:event_PanDessinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LesBilles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LesBilles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LesBilles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LesBilles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LesBilles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBas;
    private javax.swing.JButton BBille;
    private javax.swing.JButton BDroit;
    private javax.swing.JButton BGauche;
    private javax.swing.JButton BHaut;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PTitre;
    private javax.swing.JPanel PanDessin;
    // End of variables declaration//GEN-END:variables
}
