/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tp1;

/**
 *
 * @author BOBO
 */

import java.awt.* ; 

public class LesChiffres extends javax.swing.JFrame {
    private int chiffre1;
    private int chiffre2;
    private int chiffre3;
    private int numero;
    

    /**
     * Creates new form NewJFrame
     */
    public LesChiffres() {
        initComponents();
        this.chiffre1 = -1;
        this.chiffre2 = -1;
        this.numero = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        PCenter = new javax.swing.JPanel();
        LCenter = new javax.swing.JLabel();
        PSouth = new javax.swing.JPanel();
        LTaille = new javax.swing.JLabel();
        BTaille14 = new javax.swing.JButton();
        BTaille24 = new javax.swing.JButton();
        BTaille36 = new javax.swing.JButton();
        BAddition = new javax.swing.JButton();
        BSoustraction = new javax.swing.JButton();
        PWest = new javax.swing.JPanel();
        BRouge = new javax.swing.JButton();
        BJaune = new javax.swing.JButton();
        BVert = new javax.swing.JButton();
        BOrange = new javax.swing.JButton();
        BBleu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MChiffres = new javax.swing.JMenu();
        MQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LTitre.setText("Chiffres et Couleurs");
        PTitre.add(LTitre);

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PDroit.setLayout(new java.awt.GridLayout(10, 1));

        jButton0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        PDroit.add(jButton0);

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PDroit.add(jButton1);

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PDroit.add(jButton2);

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PDroit.add(jButton3);

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PDroit.add(jButton4);

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PDroit.add(jButton5);

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PDroit.add(jButton6);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        PDroit.add(jButton7);

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        PDroit.add(jButton8);

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        PDroit.add(jButton9);

        getContentPane().add(PDroit, java.awt.BorderLayout.LINE_END);

        PCenter.setLayout(new java.awt.GridLayout(1, 1));

        LCenter.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LCenter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LCenter.setText("Cliquez sur un bouton !");
        PCenter.add(LCenter);

        getContentPane().add(PCenter, java.awt.BorderLayout.CENTER);

        LTaille.setText("Tailles des caractères :");
        PSouth.add(LTaille);

        BTaille14.setText("14");
        BTaille14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaille14ActionPerformed(evt);
            }
        });
        PSouth.add(BTaille14);

        BTaille24.setText("24");
        BTaille24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaille24ActionPerformed(evt);
            }
        });
        PSouth.add(BTaille24);

        BTaille36.setText("36");
        BTaille36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTaille36ActionPerformed(evt);
            }
        });
        PSouth.add(BTaille36);

        BAddition.setText("+");
        BAddition.setPreferredSize(new java.awt.Dimension(60, 23));
        BAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAdditionActionPerformed(evt);
            }
        });
        PSouth.add(BAddition);

        BSoustraction.setText("-");
        BSoustraction.setPreferredSize(new java.awt.Dimension(60, 23));
        BSoustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSoustractionActionPerformed(evt);
            }
        });
        PSouth.add(BSoustraction);

        getContentPane().add(PSouth, java.awt.BorderLayout.PAGE_END);

        PWest.setLayout(new java.awt.GridLayout(5, 1));

        BRouge.setText("Rouge");
        BRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRougeActionPerformed(evt);
            }
        });
        PWest.add(BRouge);

        BJaune.setText("Jaune");
        BJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJauneActionPerformed(evt);
            }
        });
        PWest.add(BJaune);

        BVert.setText("Vert");
        BVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVertActionPerformed(evt);
            }
        });
        PWest.add(BVert);

        BOrange.setText("Orange");
        BOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOrangeActionPerformed(evt);
            }
        });
        PWest.add(BOrange);

        BBleu.setText("Bleu");
        BBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBleuActionPerformed(evt);
            }
        });
        PWest.add(BBleu);

        getContentPane().add(PWest, java.awt.BorderLayout.LINE_START);

        MChiffres.setText("LesChiffres");

        MQuitter.setText("Quitter");
        MQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MQuitterActionPerformed(evt);
            }
        });
        MChiffres.add(MQuitter);

        jMenuBar1.add(MChiffres);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("ZERO"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 0;
            this.numero = 2;
        }else {
            this.chiffre2 = 0;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("CINQ"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 5;
            this.numero = 2;
        }else {
            this.chiffre2 = 5;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("HUIT"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 8;
            this.numero = 2;
        }else {
            this.chiffre2 = 8;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("SIX"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 6;
            this.numero = 2;
        }else {
            this.chiffre2 =6;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("DEUX"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 2;
            this.numero = 2;
        }else {
            this.chiffre2 = 2;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("NEUF"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 9;
            this.numero = 2;
        }else {
            this.chiffre2 = 9;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("UN"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 1;
            this.numero = 2;
        }else {
            this.chiffre2 = 1;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("TROIS"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 3;
            this.numero = 2;
        }else {
            this.chiffre2 = 3;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("QUATRE"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 4;
            this.numero = 2;
        }else {
            this.chiffre2 = 4;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.green); // changement de la couleur d’écriture
        LCenter.setText("SEPT"); // changement du texte à afficher
        if(this.numero == 1){
            this.chiffre1 = 7;
            this.numero = 2;
        }else {
            this.chiffre2 = 7;
            this.numero = 1;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void BRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRougeActionPerformed
        // TODO add your handling code here:
        LCenter.setForeground(Color.red) ;
        PCenter.setBackground(new Color(0, 0, 0));

    }//GEN-LAST:event_BRougeActionPerformed

    private void BOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOrangeActionPerformed
        // TODO add your handling code here:
         LCenter.setForeground(Color.orange) ;
          PCenter.setBackground(Color.red);
    }//GEN-LAST:event_BOrangeActionPerformed

    private void BJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJauneActionPerformed
        // TODO add your handling code here:
         LCenter.setForeground(Color.yellow) ;
         PCenter.setBackground(Color.green);
    }//GEN-LAST:event_BJauneActionPerformed

    private void BVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVertActionPerformed
        // TODO add your handling code here:
         LCenter.setForeground(Color.green) ;
         PCenter.setBackground(Color.yellow);
    }//GEN-LAST:event_BVertActionPerformed

    private void MQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0 ) ;

        
    }//GEN-LAST:event_MQuitterActionPerformed

    private void BBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBleuActionPerformed
        // TODO add your handling code here:
         LCenter.setForeground(Color.blue) ;
          PCenter.setBackground(Color.pink);
    }//GEN-LAST:event_BBleuActionPerformed

    private void BTaille14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaille14ActionPerformed
        // TODO add your handling code here:
        LCenter.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_BTaille14ActionPerformed

    private void BTaille24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaille24ActionPerformed
        // TODO add your handling code here:
        LCenter.setFont(new java.awt.Font("Tahoma", 0, 24));
    }//GEN-LAST:event_BTaille24ActionPerformed

    private void BTaille36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTaille36ActionPerformed
        // TODO add your handling code here:
        LCenter.setFont(new java.awt.Font("Tahoma", 0, 36));
    }//GEN-LAST:event_BTaille36ActionPerformed

    private void BAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAdditionActionPerformed
        // TODO add your handling code here:
        if(this.chiffre1 != -1 && this.chiffre2 != -1){
            int res = this.chiffre1 + this.chiffre2;
            LCenter.setText(" " + this.chiffre1 +" + " + this.chiffre2 + " = " + res);
            this.chiffre1 = -1;
            this.chiffre2 = -1;
            this.numero = 1;
        }else{
            LCenter.setText("Cliquez sur un chiffre");
        }
    }//GEN-LAST:event_BAdditionActionPerformed

    private void BSoustractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSoustractionActionPerformed
        // TODO add your handling code here:
          if(this.chiffre1 != -1 && this.chiffre2 != -1){
            int res = this.chiffre1 - this.chiffre2;
            LCenter.setText(" " + this.chiffre1 +" - " + this.chiffre2 + " = " + res);
            this.chiffre1 = -1;
            this.chiffre2 = -1;
            this.numero = 1;
        }else{
            LCenter.setText("Cliquez sur un chiffre");
        }
    }//GEN-LAST:event_BSoustractionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LesChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LesChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LesChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LesChiffres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LesChiffres().setVisible(true);
                LesChiffres lc= new LesChiffres();
                lc.setSize(800,800) ;
                lc.setTitle("Les Chiffres");
                lc.setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAddition;
    private javax.swing.JButton BBleu;
    private javax.swing.JButton BJaune;
    private javax.swing.JButton BOrange;
    private javax.swing.JButton BRouge;
    private javax.swing.JButton BSoustraction;
    private javax.swing.JButton BTaille14;
    private javax.swing.JButton BTaille24;
    private javax.swing.JButton BTaille36;
    private javax.swing.JButton BVert;
    private javax.swing.JLabel LCenter;
    private javax.swing.JLabel LTaille;
    private javax.swing.JLabel LTitre;
    private javax.swing.JMenu MChiffres;
    private javax.swing.JMenuItem MQuitter;
    private javax.swing.JPanel PCenter;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PSouth;
    private javax.swing.JPanel PTitre;
    private javax.swing.JPanel PWest;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}


