
import java.awt.Color;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class Palette extends javax.swing.JFrame {

    /**
     * Creates new form Palette
     */
    public Palette() {
        initComponents();
        initPanneau();
    }
    private void initPanneau(){
        for(int i = 0; i < 400; i++){
            JButton bt = new JButton();
            int r = (int)(Math.random()*256);
            int v = (int)(Math.random()*256);
            int b = (int)(Math.random()*256);
            Color c = new Color(r,v,b);
            bt.setBackground(c);

            
            bt.addActionListener(new java.awt.event.ActionListener(){
                public void actionPerformed(java.awt.event.ActionEvent evt){
                    boutonActionPerformed(evt);
                    
                   


                }
            });
             PCentre.add(bt);
            
        }
}
    
    private void boutonActionPerformed(java.awt.event.ActionEvent evt){
        JButton bout = (JButton) evt.getSource();
        Color c = bout.getBackground();
         for(int i = 0; i < 400; i++){
             JButton bt = (JButton) PCentre.getComponent(i);
             bt.setBackground(c);
         }
         Rouge.setText(""+c.getRed());
         Vert.setText(""+c.getGreen());
         Bleu.setText(""+c.getBlue());
        
        
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PDroit = new javax.swing.JPanel();
        LCouleur = new javax.swing.JLabel();
        Lvide = new javax.swing.JLabel();
        LRouge = new javax.swing.JLabel();
        Rouge = new javax.swing.JLabel();
        LVert = new javax.swing.JLabel();
        Vert = new javax.swing.JLabel();
        LBleu = new javax.swing.JLabel();
        Bleu = new javax.swing.JLabel();
        BNouveau = new javax.swing.JButton();
        PCentre = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PDroit.setLayout(new java.awt.GridLayout(10, 1));

        LCouleur.setText("Couleur");
        PDroit.add(LCouleur);
        PDroit.add(Lvide);

        LRouge.setText("Rouge");
        PDroit.add(LRouge);
        PDroit.add(Rouge);

        LVert.setText("Vert");
        PDroit.add(LVert);
        PDroit.add(Vert);

        LBleu.setText("Bleu");
        PDroit.add(LBleu);
        PDroit.add(Bleu);

        BNouveau.setText("Nouveau");
        BNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNouveauActionPerformed(evt);
            }
        });
        PDroit.add(BNouveau);

        getContentPane().add(PDroit, java.awt.BorderLayout.EAST);

        PCentre.setLayout(new java.awt.GridLayout(20, 20));
        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNouveauActionPerformed
        // TODO add your handling code here:
         for(int i = 0; i < 400; i++){
             JButton bt = (JButton) PCentre.getComponent(i);
            int r = (int)(Math.random()*256);
            int v = (int)(Math.random()*256);
            int b = (int)(Math.random()*256);
            Color c = new Color(r,v,b);
            bt.setBackground(c);
         }
         Rouge.setText("");
         Vert.setText("");
         Bleu.setText("");
         
    }//GEN-LAST:event_BNouveauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Palette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Palette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Palette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Palette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Palette().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNouveau;
    private javax.swing.JLabel Bleu;
    private javax.swing.JLabel LBleu;
    private javax.swing.JLabel LCouleur;
    private javax.swing.JLabel LRouge;
    private javax.swing.JLabel LVert;
    private javax.swing.JLabel Lvide;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PDroit;
    private javax.swing.JLabel Rouge;
    private javax.swing.JLabel Vert;
    // End of variables declaration//GEN-END:variables
}
