
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author BOBO
 */
public class ClassementDlg extends javax.swing.JDialog {

    /**
     * Creates new form ClassementDlg
     */
    private LesJoueurs lesJo;
    private LesParties lesPa;
    private int tabC[]; //utilisé pour le classement des joueurs
    

    /**
     * Creates new form ClassementDlg
     */
    public ClassementDlg(java.awt.Frame parent, boolean modal, LesJoueurs lesj, LesParties lp) {
        super(parent, modal);
        initComponents();
        this.lesJo = lesj;
        this.lesPa = lp;
        Edition.setText(this.lesJo.toString());
        this.tabC = new int[this.lesJo.getNbJoueurs()];
        initClassement();
        initListeJoueursClasses();

    }

    private void initClassement() { //tri par sélection
        int max;
        for (int i = 0; i < this.lesJo.getNbJoueurs(); i++) {
            tabC[i] = i;
        }
        for (int i = 0; i < this.lesJo.getNbJoueurs() - 1; i++) {
            max = this.lesJo.getJoueur(i).getNbpartiesGagnees();
            for (int j = i + 1; j < this.lesJo.getNbJoueurs(); j++) {
                if (this.lesJo.getJoueur(j).getNbpartiesGagnees() > max) {
                    int temp = tabC[i];
                    tabC[i] = tabC[j];
                    tabC[j] = temp;
                }
            }
        }
    }

    public void paint(Graphics g) { //Pour que la méthode paint affiche l'histogramme 
        super.paint(g);
        dessineHisto();
    }

    private void initListeJoueursClasses() {
        DefaultListModel mod = new DefaultListModel();
        ListeClassement.setModel(mod);
        for (int i = 1; i < lesJo.getNbJoueurs(); i++) {
            mod.addElement("" + i +" "+ this.lesJo.getJoueur(tabC[i]).getPseudo());
        }
    }

    private void dessineHisto() {
        Graphics g = PanHisto.getGraphics();
        int nbJo = this.lesJo.getNbJoueurs();
        int nbPa = this.lesPa.getNbPartie();
     
        int largeurMax = this.getWidth() / 2;
        int decalageLarg = 50;
        int decalageHaut = 50;
        int largRect = largeurMax / nbJo;
        int hautMax = this.PanHisto.getHeight() / 2;

        for (int i = 0; i < nbJo; i++) {
            Joueur j = this.lesJo.getJoueur(i);
            int nbPartG = j.getNbpartiesGagnees();
            int hautRectJ;
            if (nbPartG == 0) {
                hautRectJ = 10;
            } else {
                hautRectJ = hautMax * nbPartG / nbPa;
            }
            int r = (int) (Math.random() * 255);
            int v = (int) (Math.random() * 255);
            int b = (int) (Math.random() * 255);
            g.setColor(new Color(r, v, b));
            g.drawString(j.getPseudo(), decalageLarg + i * largRect, hautMax + decalageHaut + 20);
            g.drawString("" + nbPartG, decalageLarg + i * largRect, hautMax + decalageHaut + 30);
            g.fillRect(decalageLarg + i * largRect, hautMax + decalageHaut - hautRectJ, largRect, hautRectJ);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeClassement = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        PanHisto = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Statistique des joueurs");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTitreLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(LTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTitreLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(LTitre)
                .addGap(35, 35, 35))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PDroit.setLayout(new java.awt.GridLayout(2, 1));

        jScrollPane1.setViewportView(ListeClassement);

        PDroit.add(jScrollPane1);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        PDroit.add(jScrollPane2);

        getContentPane().add(PDroit, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout PanHistoLayout = new javax.swing.GroupLayout(PanHisto);
        PanHisto.setLayout(PanHistoLayout);
        PanHistoLayout.setHorizontalGroup(
            PanHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        PanHistoLayout.setVerticalGroup(
            PanHistoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        getContentPane().add(PanHisto, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel LTitre;
    private javax.swing.JList<String> ListeClassement;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PTitre;
    private javax.swing.JPanel PanHisto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
