
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {
    private Joueur nj;
    private boolean ok;
    private ImageIcon photo;

    /**
     * Creates new form SaisieJoueursDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.nj = new Joueur();
        BPhoto.setIcon(this.nj.getPhoto());
        this.photo = this.nj.getPhoto();
    }
    public Joueur getJoueur(){
        return this.nj;
    }
    public boolean getOk(){
        return this.ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PHautGauche = new javax.swing.JPanel();
        LPseudo = new javax.swing.JLabel();
        PHautDroit = new javax.swing.JPanel();
        PSeudo = new javax.swing.JTextField();
        PBasGauche = new javax.swing.JPanel();
        LPhoto = new javax.swing.JLabel();
        BParcourir = new javax.swing.JButton();
        PBasDroit = new javax.swing.JPanel();
        BPhoto = new javax.swing.JButton();
        PSud = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Ajout d'un nouveau Joueur");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(LTitre)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(LTitre)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PCentre.setLayout(new java.awt.GridLayout(2, 2));

        PHautGauche.setLayout(new java.awt.GridLayout(1, 2));

        LPseudo.setText("PSeudo ?");
        PHautGauche.add(LPseudo);

        PCentre.add(PHautGauche);

        PSeudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSeudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PHautDroitLayout = new javax.swing.GroupLayout(PHautDroit);
        PHautDroit.setLayout(PHautDroitLayout);
        PHautDroitLayout.setHorizontalGroup(
            PHautDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
            .addGroup(PHautDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PHautDroitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PSeudo, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        PHautDroitLayout.setVerticalGroup(
            PHautDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
            .addGroup(PHautDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PHautDroitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PSeudo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PCentre.add(PHautDroit);

        PBasGauche.setLayout(new java.awt.GridLayout(1, 2));

        LPhoto.setText("Photo ?");
        PBasGauche.add(LPhoto);

        BParcourir.setText("Parcourir");
        BParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BParcourirActionPerformed(evt);
            }
        });
        PBasGauche.add(BParcourir);

        PCentre.add(PBasGauche);

        javax.swing.GroupLayout PBasDroitLayout = new javax.swing.GroupLayout(PBasDroit);
        PBasDroit.setLayout(PBasDroitLayout);
        PBasDroitLayout.setHorizontalGroup(
            PBasDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
            .addGroup(PBasDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PBasDroitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );
        PBasDroitLayout.setVerticalGroup(
            PBasDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
            .addGroup(PBasDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PBasDroitLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        PCentre.add(PBasDroit);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        PSud.add(BValider);

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        PSud.add(BAnnuler);

        getContentPane().add(PSud, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PSeudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSeudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSeudoActionPerformed

    private void BParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BParcourirActionPerformed
        // TODO add your handling code here:
        JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(BPhoto.getWidth()-10, BPhoto.getHeight()-10, Image.SCALE_DEFAULT);
            this.photo = new ImageIcon(img);
            BPhoto.setIcon(photo);
        } 
    }//GEN-LAST:event_BParcourirActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        this.nj.setPseudo(PSeudo.getText());
        this.nj.setPhoto(this.photo);
        this.ok = true;
        this.setVisible(false);
        this.dispose();
        BPhoto.setIcon(this.nj.getPhoto());
        this.photo = this.nj.getPhoto();
     
    }//GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.ok = false;
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BParcourir;
    private javax.swing.JButton BPhoto;
    private javax.swing.JButton BValider;
    private javax.swing.JLabel LPhoto;
    private javax.swing.JLabel LPseudo;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel PBasDroit;
    private javax.swing.JPanel PBasGauche;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PHautDroit;
    private javax.swing.JPanel PHautGauche;
    private javax.swing.JTextField PSeudo;
    private javax.swing.JPanel PSud;
    private javax.swing.JPanel PTitre;
    // End of variables declaration//GEN-END:variables
}
