
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author BOBO
 */
public class ScoresDlg extends javax.swing.JDialog {

    //Attributs
    private LesJoueurs lj;
    private Joueur j;

    /**
     * Creates new form Scores
     */
    //Constructeurs
    public ScoresDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj) {
        super(parent, modal); //appel du contructeur de la classe parent qui est la jdialog
        initComponents();// creation de l'interface par l'IDE
        this.lj = lj;//initialisation de la liste des joueurs
        this.j = this.lj.getJoueur(0);//on l'initialise par le joueur en haut de la liste
        initListesJoueurs(); //appel de la methode qui remplie la jlist par le nom des joueurs
        afficheJoueur();//Methode qui affiche les informations des joueurs sur les composants
        PDroit.setPreferredSize(new Dimension(200, 200));//fixe la dimension du panneau a droite 
        //sinon elle change de taille en fonction de la photo affichée

    }

    public void initListesJoueurs() { //methode qui remplie la jlist par le nom des joueurs
        DefaultListModel mod = new DefaultListModel();
        ListJoueurs.setModel(mod);
        for (int i = 0; i < this.lj.getNbJoueurs(); i++) {

            mod.addElement(this.lj.getJoueur(i).getPseudo());
        }

    }
//Affichage de la photo d'un joueur donné
    public void afficheJoueur() {
        BGalerie.setIcon(this.j.getPhoto());

    }

    public void paint(Graphics g) { //Pour que la méthode paint affiche le camenbert 
        super.paint(g);

        dessineHisto();

    }

    private void dessineHisto() {
        Graphics g = PCentre.getGraphics();

        int largeurMax = this.getWidth() / 2; //largeur de la fenetre divisé par 2
        int decalageLarg = 50;
        int decalageHaut = 50;
        int largRect = largeurMax / 3; //largeur de la barre, on divise par 3 parce que c'est 3 barres.
        int hautMax = this.PCentre.getHeight() / 2; //demi de la hauteur du panneau au centre ou on place l'histo.

        // On récupère les vraies valeurs directement du joueur !
        int gagne = j.getNbpartiesGagnees();
        int perdu = j.getNbpartiesPerdues();
        int nul = j.getNbpartiesNul();

        int[] valeurs = {gagne, perdu, nul};
        String[] labels = {"Gagné", "Perdu", "Nul"};
        
        int max = Math.max(1, gagne + perdu + nul); // pour éviter division par 0

        for (int i = 0; i < 3; i++) {
            int h;
            if (valeurs[i] == 0) {
                h = 10; //quand c'est 0 pour avoir une petite barre sur l'histogramme
            } else {
                h = hautMax * valeurs[i] / max;
            }
            //couleur pour les barres de l'histogramme
            int r = (int) (Math.random() * 255);
            int v = (int) (Math.random() * 255);
            int b = (int) (Math.random() * 255);
            g.setColor(new Color(r, v, b)); //applique cette couleur au dessin

            // Numéro juste au-dessus de la barre
            g.drawString("" + valeurs[i],
                    decalageLarg + i * largRect + largRect / 2 - 5,
                    hautMax + decalageHaut -h-5);

            // Label en dessous
            g.drawString(labels[i],
                    decalageLarg + i * largRect,
                    hautMax + decalageHaut + 20);

            // Dessin de la barre
            int x = decalageLarg + i * largRect;
            int y = hautMax + decalageHaut - h;
            g.fillRect(x, y, largRect, h);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListJoueurs = new javax.swing.JList<>();
        BGalerie = new javax.swing.JButton();
        PCentre = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Scores des Joueurs");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTitreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTitreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PDroit.setLayout(new java.awt.GridLayout(2, 1));

        ListJoueurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListJoueursMouseClicked(evt);
            }
        });
        ListJoueurs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListJoueursValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListJoueurs);

        PDroit.add(jScrollPane1);
        PDroit.add(BGalerie);

        getContentPane().add(PDroit, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout PCentreLayout = new javax.swing.GroupLayout(PCentre);
        PCentre.setLayout(PCentreLayout);
        PCentreLayout.setHorizontalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );
        PCentreLayout.setVerticalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListJoueursValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListJoueursValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ListJoueursValueChanged
//Clique sur un element de la liste
    private void ListJoueursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListJoueursMouseClicked
        // TODO add your handling code here:
        int ind = ListJoueurs.getSelectedIndex();
        this.j = this.lj.getJoueur(ind);
        afficheJoueur(); //pour la photo
        this.repaint();//pour qu'a chaque clic ca redessine l'histogramme

    }//GEN-LAST:event_ListJoueursMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoresDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoresDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoresDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoresDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGalerie;
    private javax.swing.JLabel LTitre;
    private javax.swing.JList<String> ListJoueurs;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PTitre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
