/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class ModifPeintureDlg extends javax.swing.JDialog {

    /**
     * Creates new form ModifPeintureDlg
     */
    public ModifPeintureDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHaut = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PGauchCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPeinture = new javax.swing.JList<>();
        PPeinture = new javax.swing.JButton();
        PDroitCentre = new javax.swing.JPanel();
        PGaucheD = new javax.swing.JPanel();
        LGenerateur = new javax.swing.JLabel();
        LAuteur = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        LPeinture = new javax.swing.JLabel();
        PDroitD = new javax.swing.JPanel();
        PPetit = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        ComboGenerateur = new javax.swing.JComboBox<>();
        TAuteur = new javax.swing.JTextField();
        TTitre = new javax.swing.JTextField();
        BParcourir = new javax.swing.JButton();
        PSouth = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();
        Message = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Modifier une peinture");

        javax.swing.GroupLayout PHautLayout = new javax.swing.GroupLayout(PHaut);
        PHaut.setLayout(PHautLayout);
        PHautLayout.setHorizontalGroup(
            PHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(PHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHautLayout.createSequentialGroup()
                    .addContainerGap(207, Short.MAX_VALUE)
                    .addComponent(LTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        PHautLayout.setVerticalGroup(
            PHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PHautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHautLayout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        getContentPane().add(PHaut, java.awt.BorderLayout.PAGE_START);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        PGauchCentre.setLayout(new java.awt.GridLayout(2, 1));

        ListPeinture.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListPeinture);

        PGauchCentre.add(jScrollPane1);

        PPeinture.setText("jButton1");
        PGauchCentre.add(PPeinture);

        PCentre.add(PGauchCentre);

        PDroitCentre.setLayout(new java.awt.GridLayout(1, 0));

        PGaucheD.setLayout(new java.awt.GridLayout(4, 1));

        LGenerateur.setText("Generateur ?");
        PGaucheD.add(LGenerateur);

        LAuteur.setText("Auteur ?");
        PGaucheD.add(LAuteur);

        titre.setText("Titre ?");
        PGaucheD.add(titre);

        LPeinture.setText("Peinture ?");
        PGaucheD.add(LPeinture);

        PDroitCentre.add(PGaucheD);

        PDroitD.setLayout(new java.awt.GridLayout(4, 1));

        PPetit.setLayout(new java.awt.GridLayout(2, 1));

        jTextField3.setText("TGenerateur");
        PPetit.add(jTextField3);

        ComboGenerateur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PPetit.add(ComboGenerateur);

        PDroitD.add(PPetit);

        TAuteur.setText("HHH");
        PDroitD.add(TAuteur);

        TTitre.setText("jTextField2");
        PDroitD.add(TTitre);

        BParcourir.setText("Parcourir");
        PDroitD.add(BParcourir);

        PDroitCentre.add(PDroitD);

        PCentre.add(PDroitCentre);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        BValider.setText("Valider");
        PSouth.add(BValider);

        BAnnuler.setText("Annuler");
        PSouth.add(BAnnuler);
        PSouth.add(Message);

        getContentPane().add(PSouth, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifPeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifPeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifPeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifPeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModifPeintureDlg dialog = new ModifPeintureDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BParcourir;
    private javax.swing.JButton BValider;
    private javax.swing.JComboBox<String> ComboGenerateur;
    private javax.swing.JLabel LAuteur;
    private javax.swing.JLabel LGenerateur;
    private javax.swing.JLabel LPeinture;
    private javax.swing.JLabel LTitre;
    private javax.swing.JList<String> ListPeinture;
    private javax.swing.JTextField Message;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PDroitCentre;
    private javax.swing.JPanel PDroitD;
    private javax.swing.JPanel PGauchCentre;
    private javax.swing.JPanel PGaucheD;
    private javax.swing.JPanel PHaut;
    private javax.swing.JButton PPeinture;
    private javax.swing.JPanel PPetit;
    private javax.swing.JPanel PSouth;
    private javax.swing.JTextField TAuteur;
    private javax.swing.JTextField TTitre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
