/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class VisuJoueurDlg extends javax.swing.JDialog {
    private LesJoueurs lj;
    private Joueur joueurCourant;

    /**
     * Creates new form VisuJoueurDlg
     */
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal,LesJoueurs llj) {
        super(parent, modal);
        initComponents();
        this.lj = llj;
        this.joueurCourant = this.lj.getJoueur(0);
        afficheJoueurCourant();
        initListJoueur();
    }
    public void initListJoueur(){
        for(int i = 0; i < this.lj.getNbJoueurs();i++){
            ListeJoueur.addItem(this.lj.getJoueur(i).getPseudo());
        }
    }
    public void afficheJoueurCourant(){
        PSeudo.setText(this.joueurCourant.getPseudo());
        Niveau.setText(""+this.joueurCourant.getNiveau());
        BPhoto.setIcon(this.joueurCourant.getPhoto());
        Edition.setText(this.joueurCourant.toString());
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNord = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        ListeJoueur = new javax.swing.JComboBox<>();
        PCentre = new javax.swing.JPanel();
        PGauche = new javax.swing.JPanel();
        PHautGauche = new javax.swing.JPanel();
        PSeudo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Niveau = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BPhoto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Joueur à visualiser");
        PNord.add(LTitre);

        ListeJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeJoueurActionPerformed(evt);
            }
        });
        PNord.add(ListeJoueur);

        getContentPane().add(PNord, java.awt.BorderLayout.PAGE_START);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        PGauche.setLayout(new java.awt.GridLayout(2, 1));

        PHautGauche.setLayout(new java.awt.GridLayout(2, 2));

        PSeudo.setText("PSeudo:");
        PHautGauche.add(PSeudo);
        PHautGauche.add(jLabel2);

        Niveau.setText("Niveau:");
        PHautGauche.add(Niveau);
        PHautGauche.add(jLabel4);

        PGauche.add(PHautGauche);

        BPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhotoActionPerformed(evt);
            }
        });
        PGauche.add(BPhoto);

        PCentre.add(PGauche);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        PCentre.add(jScrollPane1);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListeJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeJoueurActionPerformed
        // TODO add your handling code here:
        int ind = ListeJoueur.getSelectedIndex();
        this.joueurCourant = this.lj.getJoueur(ind);
        afficheJoueurCourant();
    }//GEN-LAST:event_ListeJoueurActionPerformed

    private void BPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPhoto;
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel LTitre;
    private javax.swing.JComboBox<String> ListeJoueur;
    private javax.swing.JLabel Niveau;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PGauche;
    private javax.swing.JPanel PHautGauche;
    private javax.swing.JPanel PNord;
    private javax.swing.JLabel PSeudo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
