
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class SaisiePeintureDlg extends javax.swing.JDialog {
    
    
    private PeintureIA pn; //La peinture à creer 
    private boolean ok; // boolean si truer c'est valider et false annuler


    public PeintureIA getPn() {
        return pn;
    }

    public boolean getOk() {
        return ok;
    }
    
    

    /**
     * Creates new form SaisiePeintureDlg
     */
    public SaisiePeintureDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.pn = new PeintureIA(); //je le cree dans la classe peinture;
        this.ok = false;
        BPeinture.setIcon(new ImageIcon("/src/img/ImageDefaut.jpg"));
       // initListeAuteurs(); 
        //initListeGenerateurs();
    }
   // private void initListeAuteurs() {
     //   for (int i=0; i<listeAuteur; i++)
       
        
   // }
 
    //le rôle de getAuteur est de recuperer la liste des auteurs sans doublon.
    public ArrayList<String> getAuteurs(ArrayList<PeintureIA> lstP)
    {   ArrayList<String> lst = new ArrayList<>();
        for (int i=0; i<lstP.size(); i++)
        {   PeintureIA p = lstP.get(i);
            boolean trouve = false;
            for (int j=0; j< lst.size(); j++)

                if (lst.get(j).equals(p.getAuteur()))
                trouve = true;       
            if (!trouve) lst.add(p.getAuteur()); 
        }
        return lst;    
    }
    
    /*  private void initListeGenerateurs() {
       DefaultListModel mod = (DefaultListModel) ListGenerateur.getModel();
       for(int i = 0; i< ListGenerateur)
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PCentre = new javax.swing.JPanel();
        PGauche = new javax.swing.JPanel();
        LGenerateur = new javax.swing.JLabel();
        LAuteur = new javax.swing.JLabel();
        LTitre = new javax.swing.JLabel();
        LPeinture = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListGenerateur = new javax.swing.JList<>();
        PCombo = new javax.swing.JPanel();
        ListeAuteur = new javax.swing.JComboBox<>();
        FieldAuteur = new javax.swing.JTextField();
        FieldTitre = new javax.swing.JTextField();
        PBouton = new javax.swing.JPanel();
        BParcourir = new javax.swing.JButton();
        BPeinture = new javax.swing.JButton();
        Phaut = new javax.swing.JPanel();
        LHaut = new javax.swing.JLabel();
        PSud = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();
        Message = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        PGauche.setLayout(new java.awt.GridLayout(4, 1));

        LGenerateur.setText("Generateur ?");
        PGauche.add(LGenerateur);

        LAuteur.setText("Auteur ?");
        PGauche.add(LAuteur);

        LTitre.setText("Titre ?");
        PGauche.add(LTitre);

        LPeinture.setText("Peinture ?");
        PGauche.add(LPeinture);

        PCentre.add(PGauche);

        PDroit.setLayout(new java.awt.GridLayout(4, 1));

        ListGenerateur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListGenerateur);

        PDroit.add(jScrollPane1);

        PCombo.setLayout(new java.awt.GridLayout(2, 1));

        ListeAuteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListeAuteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeAuteurActionPerformed(evt);
            }
        });
        PCombo.add(ListeAuteur);
        PCombo.add(FieldAuteur);

        PDroit.add(PCombo);
        PDroit.add(FieldTitre);

        PBouton.setLayout(new java.awt.GridLayout(1, 2));

        BParcourir.setText("Parcourir");
        BParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BParcourirActionPerformed(evt);
            }
        });
        PBouton.add(BParcourir);
        PBouton.add(BPeinture);

        PDroit.add(PBouton);

        PCentre.add(PDroit);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        LHaut.setText("Saisie d'une nouvelle peinture");

        javax.swing.GroupLayout PhautLayout = new javax.swing.GroupLayout(Phaut);
        Phaut.setLayout(PhautLayout);
        PhautLayout.setHorizontalGroup(
            PhautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(PhautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhautLayout.createSequentialGroup()
                    .addContainerGap(155, Short.MAX_VALUE)
                    .addComponent(LHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );
        PhautLayout.setVerticalGroup(
            PhautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PhautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhautLayout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(LHaut)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );

        getContentPane().add(Phaut, java.awt.BorderLayout.PAGE_START);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        PSud.add(BValider);

        BAnnuler.setText("Annuler");
        PSud.add(BAnnuler);

        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        PSud.add(Message);

        getContentPane().add(PSud, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BParcourirActionPerformed
        // TODO add your handling code here:
           JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
        {   String path = jf.getSelectedFile().getPath(); 
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            img=img.getScaledInstance(BPeinture.getWidth()-10, BPeinture.getHeight()-10, Image.SCALE_DEFAULT);
            ImageIcon imc= new ImageIcon(img);
            BPeinture.setIcon(imc);
        }    

        
    }//GEN-LAST:event_BParcourirActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessageActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        if((ListGenerateur.getSelectedIndex()!=-1) && !(FieldAuteur.getText().equals("")) && !(FieldTitre.getText().equals("")) ){
            this.pn.setAuteur(this.pn.getAuteur());
            this.pn.setGenerateur(this.pn.getGenerateur());
            this.pn.setTitre(this.pn.getTitre());
            BPeinture.setIcon(this.pn.getPeinture());
            this.ok = true;
            this.setVisible(false);
            this.dispose();
            
        }else
            Message.setText("Erreur");
        
       // if(ListGenerateur.getSelectedValue())
    }//GEN-LAST:event_BValiderActionPerformed

    private void ListeAuteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeAuteurActionPerformed
        // TODO add your handling code here:
        String nom = ListeAuteur.getSelectedItem().toString();
        FieldAuteur.setText(nom);
    }//GEN-LAST:event_ListeAuteurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisiePeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisiePeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisiePeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisiePeintureDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisiePeintureDlg dialog = new SaisiePeintureDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BParcourir;
    private javax.swing.JButton BPeinture;
    private javax.swing.JButton BValider;
    private javax.swing.JTextField FieldAuteur;
    private javax.swing.JTextField FieldTitre;
    private javax.swing.JLabel LAuteur;
    private javax.swing.JLabel LGenerateur;
    private javax.swing.JLabel LHaut;
    private javax.swing.JLabel LPeinture;
    private javax.swing.JLabel LTitre;
    private javax.swing.JList<String> ListGenerateur;
    private javax.swing.JComboBox<String> ListeAuteur;
    private javax.swing.JTextField Message;
    private javax.swing.JPanel PBouton;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PCombo;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PGauche;
    private javax.swing.JPanel PSud;
    private javax.swing.JPanel Phaut;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
