/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Millimouno
 */
import java.awt.Image;
import javax.swing.*;
public class BatailleDlg extends javax.swing.JDialog {

    /**
     * Creates new form BatailleDlg
     */
    /*public BatailleDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }*/
     private LesJoueurs lj; //collection des joueurs (en entrée)
    private int indj; //indice du joueur courant (en entrée)
    private Joueur adversaire; //adversaire sélectionné (en sortie)
    private boolean ok; // action faite ou non (en sortie)
    private Bataille b; // action réalisée

        public BatailleDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj, int jc) {
        super(parent, modal);
        initComponents();
        this.lj = lj;
        this.indj = jc;
        this.ok=true;
        this.b=null;
        int index=jList1.getSelectedIndex();
        this.adversaire=this.lj.getJoueur(index);
        
        
        initListeJ();
        Annuler.setText("Annuler"); Annuler.setVisible(false); // pas de bataille
        MessageJ.setText(lj.getJoueur(indj).getPseudo()+" va effectuer une bataille contre : ");
        
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            ListeJMouseClicked(evt);
        }
        });

    }

    
    public boolean isOk() { return ok; }
    public Joueur getAdversaire() { return this.adversaire; }
    public Bataille getBataille(){ return b;}
    public void initListeJ(){
        DefaultListModel mod = new DefaultListModel();
        jList1.setModel(mod);
        //mod.addElement(lj.getJoueur(indj).getPseudo());
        for(int i=0; i<lj.getNbJoueurs();i++){
            mod.addElement(lj.getJoueur(i).getPseudo());
        }
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//mod.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public void ListeJMouseClicked(java.awt.event.MouseEvent evt){
        Joueur j = new Joueur();
        j = lj.getJoueur(indj);
        if(jList1.getSelectedIndex()== lj.getIndiceJoueur(j)){
           MessageJ.setText("Le Joueur courant ne doit pas être sélectionée") ;
        }
        else
        {
            int index = jList1.getSelectedIndex();
            this.adversaire= lj.getJoueur(index);
            this.b = new Bataille(this.lj.getJoueur(indj),this.getAdversaire());
            Annuler.setVisible(true);
            Joueur.setText(this.lj.getJoueur(indj).getPseudo());
            Adversaire.setText(this.getAdversaire().getPseudo());
            InfosCarte1.setText(this.lj.getJoueur(indj).getPaquet().toString());
            InfoCarte2.setText(this.getAdversaire().getPaquet().toString());
        }
            
    }
    //private void initComponents(){. . .};
    
        
        
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MessageJ = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Joueur = new javax.swing.JLabel();
        Adversaire = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfosCarte1 = new javax.swing.JTextArea();
        Carte1 = new javax.swing.JButton();
        Carte2 = new javax.swing.JButton();
        Ic2 = new javax.swing.JScrollPane();
        InfoCarte2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        Vainqueur = new javax.swing.JLabel();
        Annuler = new javax.swing.JButton();
        Demarer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));
        jPanel1.add(MessageJ);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Joueur.setText("Joueur");
        jPanel3.add(Joueur);

        Adversaire.setText("Adversaire");
        jPanel3.add(Adversaire);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        InfosCarte1.setColumns(20);
        InfosCarte1.setLineWrap(true);
        InfosCarte1.setRows(5);
        InfosCarte1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(InfosCarte1);

        jPanel4.add(jScrollPane1);
        jPanel4.add(Carte1);
        jPanel4.add(Carte2);

        InfoCarte2.setColumns(20);
        InfoCarte2.setLineWrap(true);
        InfoCarte2.setRows(5);
        InfoCarte2.setToolTipText("");
        InfoCarte2.setWrapStyleWord(true);
        Ic2.setViewportView(InfoCarte2);

        jPanel4.add(Ic2);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(1, 3));
        jPanel5.add(Vainqueur);

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel5.add(Annuler);

        Demarer.setText("Demarer");
        Demarer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarerActionPerformed(evt);
            }
        });
        jPanel5.add(Demarer);

        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemarerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarerActionPerformed
        // TODO add your handling code here:
        //Affichage des premières cartes de chaque joueur
        InfosCarte1.append(this.lj.getJoueur(indj).getPaquet().getPerso(0).toString()+"\n\n");
        InfoCarte2.append(this.adversaire.getPaquet().getPerso(0).toString()+"\n\n");
        int res=b.execute();
        if(res!=-1){
            System.out.println(this.lj.getJoueur(indj));
            System.out.println(this.adversaire);
            //lancement d la bataille
            if(res==1){ // le joueur courant est le gagnant
               Vainqueur.setText("Le joueur qui à gangné est: "+lj.getJoueur(indj).getPseudo()); 
                this.ok=true;
            }
            if(res==2){ // l'adversaire est le gagant
                Vainqueur.setText("Le joueur qui à gangné est: "+this.adversaire.getPseudo()); 
                this.ok=true;
            }
            if(res==0){ // Macth nul
               Vainqueur.setText("Match nul");
                this.ok=true;
            }
            //aficher la nouvelle mise à jour des paquets après la bataille
            
            
            //si l'un d'entre eux n'a plus de carte
            if(this.getAdversaire().getPaquet().getTaille()== 0 || this.lj.getJoueur(indj).getPaquet().getTaille()== 0){
                
                Demarer.setEnabled(false);
                Annuler.setText("Fermer");
            }
            InfosCarte1.append(this.lj.getJoueur(indj).getPaquet().toString());
            InfoCarte2.append(this.getAdversaire().getPaquet().toString());
               
            if(this.lj.getJoueur(indj).getPaquet().getTaille()!=0 && this.getAdversaire().getPaquet().getTaille()!=0){
                Carte1.setIcon(new ImageIcon(lj.getJoueur(indj).getPaquet().getPerso(0).getPhoto().getScaledInstance(Carte1.getWidth(), Carte1.getHeight(), Image.SCALE_SMOOTH)));
                Carte2.setIcon(new ImageIcon(this.getAdversaire().getPaquet().getPerso(0).getPhoto().getScaledInstance(Carte2.getWidth(), Carte2.getHeight(), Image.SCALE_SMOOTH)));
            }
            System.out.println(this.lj.getJoueur(indj).getPaquet());
            System.out.println(this.getAdversaire().getPaquet());
        }
    }//GEN-LAST:event_DemarerActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.ok=false;
        if (Annuler.getText().equals("Annuler"))
        this.b.setDeroulement("Bataille interrompue en cours de partie");
        this.setVisible(false); this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatailleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatailleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatailleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatailleDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BatailleDlg dialog = new BatailleDlg(new javax.swing.JFrame(), true,null,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adversaire;
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Carte1;
    private javax.swing.JButton Carte2;
    private javax.swing.JButton Demarer;
    private javax.swing.JScrollPane Ic2;
    private javax.swing.JTextArea InfoCarte2;
    private javax.swing.JTextArea InfosCarte1;
    private javax.swing.JLabel Joueur;
    private javax.swing.JLabel MessageJ;
    private javax.swing.JLabel Vainqueur;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
