
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author sb241966
 */
public class InitDlg extends javax.swing.JDialog {
    private int nc ;
    private LesJoueurs lj;
    private boolean ok;

    public int getNc() {
        return nc;
    }

    public LesJoueurs getLj() {
        return lj;
    }

    public boolean isOk() {
        return ok;
    }
  
    /**
     * Creates new form InitDlg
     * @param parent
     * @param modal
     */
    public InitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.lj=new LesJoueurs();
        this.ok=false;
        this.nc=4;
        Enfants.setSelected(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Groupe1 = new javax.swing.ButtonGroup();
        Groupe2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Enfants = new javax.swing.JRadioButton();
        Debutant = new javax.swing.JRadioButton();
        Avancé = new javax.swing.JRadioButton();
        Expert = new javax.swing.JRadioButton();
        titre1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        CLara = new javax.swing.JCheckBox();
        CJack = new javax.swing.JCheckBox();
        CJean = new javax.swing.JCheckBox();
        CAmadeus = new javax.swing.JCheckBox();
        titre2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        JS = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        Groupe1.add(Enfants);
        Enfants.setText("enfant (4 personnages, 2 Familles)");
        Enfants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfantsActionPerformed(evt);
            }
        });
        jPanel3.add(Enfants);

        Groupe1.add(Debutant);
        Debutant.setText("débutant (10 personnages, 2 familles)");
        Debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebutantActionPerformed(evt);
            }
        });
        jPanel3.add(Debutant);

        Groupe1.add(Avancé);
        Avancé.setText("avancé (18 personnages, 4 familles)");
        Avancé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvancéActionPerformed(evt);
            }
        });
        jPanel3.add(Avancé);

        Groupe1.add(Expert);
        Expert.setText("expert (32 personnages, 6 familles)");
        Expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertActionPerformed(evt);
            }
        });
        jPanel3.add(Expert);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        titre1.setText("Choisissez la taille du jeu");
        jPanel2.add(titre1, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        CLara.setText("Lara");
        CLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLaraActionPerformed(evt);
            }
        });
        jPanel5.add(CLara);

        CJack.setText("Jack");
        CJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CJackActionPerformed(evt);
            }
        });
        jPanel5.add(CJack);

        CJean.setText("Jean-Sébastien");
        CJean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CJeanActionPerformed(evt);
            }
        });
        jPanel5.add(CJean);

        CAmadeus.setText("Amadeus");
        CAmadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAmadeusActionPerformed(evt);
            }
        });
        jPanel5.add(CAmadeus);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        titre2.setText("Choisissez les joueurs crées par défaut");
        jPanel4.add(titre2, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setLineWrap(true);
        Edition.setRows(5);
        Edition.setWrapStyleWord(true);
        JS.setViewportView(Edition);

        jPanel6.add(JS);

        BPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPhotoActionPerformed(evt);
            }
        });
        jPanel6.add(BPhoto);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel7.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel7.add(Valider);

        getContentPane().add(jPanel7, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnfantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfantsActionPerformed
        // TODO add your handling code here:
        this.nc=4;
    }//GEN-LAST:event_EnfantsActionPerformed

    private void DebutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebutantActionPerformed
        // TODO add your handling code here:
        this.nc=10;
    }//GEN-LAST:event_DebutantActionPerformed

    private void AvancéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvancéActionPerformed
        // TODO add your handling code here:
        this.nc=18;
    }//GEN-LAST:event_AvancéActionPerformed

    private void ExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertActionPerformed
        // TODO add your handling code here:
        this.nc=32;
    }//GEN-LAST:event_ExpertActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        if(CLara.isSelected()){
            Joueur j=new Joueur("Lara","équipes");
            j.setPhoto(new ImageIcon(getClass().getResource("Img/lara.jpg")));
            lj.ajouteJoueur(j);
            System.out.println(j.getPseudo()+" a été ajouté et sa famille préférée est : "+j.getFamillePref());
            this.dispose();
        }
        if(CJack.isSelected()){
           Joueur j=new Joueur("Jack","rares");
            j.setPhoto(new ImageIcon(getClass().getResource("/Img/jack.png")));
            lj.ajouteJoueur(j);
             System.out.println(j.getPseudo()+" a été ajouté et sa famille préférée est : "+j.getFamillePref());
            this.dispose();
        }
        if(CJean.isSelected()){
            Joueur j=new Joueur("Jean-Sébastien","alpins-femmes");
            j.setPhoto(new ImageIcon(getClass().getResource("Img/Jean-Sébastien.jpg")));
            lj.ajouteJoueur(j);
             System.out.println(j.getPseudo()+" a été ajouté et sa famille préférée est : "+j.getFamillePref());
            this.dispose();
            }
        if(CAmadeus.isSelected()){
            Joueur j=new Joueur("Amadeus","communs");
            j.setPhoto(new ImageIcon(getClass().getResource("Img/mozart.jpg")));
            lj.ajouteJoueur(j);
             System.out.println(j.getPseudo()+" a été ajouté et sa famille préférée est : "+j.getFamillePref());
            this.dispose();
            
        }
        this.ok=true;
        
    }//GEN-LAST:event_ValiderActionPerformed

    private void CLaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLaraActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Lara", "epiques");
        j.setPhoto(new ImageIcon(getClass().getResource("Img/lara.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CLaraActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    private void CJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CJackActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("jack", "rares");
        j.setPhoto(new ImageIcon(getClass().getResource("Img/jack.png")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));

    }//GEN-LAST:event_CJackActionPerformed

    private void CJeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CJeanActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Jean-Sébastien", "alpins-femmes");
        j.setPhoto(new ImageIcon(getClass().getResource("Img/Jean-Sébastien.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CJeanActionPerformed

    private void CAmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAmadeusActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Amadeus", "communs");
        j.setPhoto(new ImageIcon(getClass().getResource("Img/mozart.jpg")));
        Edition.setText(j.toString());
        Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);
        BPhoto.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_CAmadeusActionPerformed

    private void BPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDlg dialog = new InitDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton Avancé;
    private javax.swing.JButton BPhoto;
    private javax.swing.JCheckBox CAmadeus;
    private javax.swing.JCheckBox CJack;
    private javax.swing.JCheckBox CJean;
    private javax.swing.JCheckBox CLara;
    private javax.swing.JRadioButton Debutant;
    private javax.swing.JTextArea Edition;
    private javax.swing.JRadioButton Enfants;
    private javax.swing.JRadioButton Expert;
    private javax.swing.ButtonGroup Groupe1;
    private javax.swing.ButtonGroup Groupe2;
    private javax.swing.JScrollPane JS;
    private javax.swing.JButton Valider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel titre1;
    private javax.swing.JLabel titre2;
    // End of variables declaration//GEN-END:variables
}
