/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author sb241966
 */
public class JeuMemory extends javax.swing.JFrame {
    private LesPersonnages persos;
    private LesJoueurs joueurs;
    private int niveau1;
    //private Joueur j;
    private Jeu jeu;
    private int l1,c1,l2,c2;
   private PlateauJeu plateau;
    /**
     * Creates new form JeuMemory
     */
    public JeuMemory(){ 
        initComponents();
        this.persos=new LesPersonnages(4);
        this.joueurs=new LesJoueurs();
        /*Joueur j1=new Joueur("Lara", "epiques");
        j1.setPhoto(new ImageIcon(getClass().getResource("Img/lara.jpg")));
        Joueur j2=new Joueur("jack", "rares");
        j2.setPhoto(new ImageIcon(getClass().getResource("Img/jack.png")));
        joueurs.ajouteJoueur(j2);
        joueurs.ajouteJoueur(j1);*/
        this.l1=-1;this.c1=-1;this.c2=-1;this.l2=-1;
        this.jeu=new Jeu(this.persos,this.joueurs,4);
        this.plateau=this.jeu.getPlateau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NbPersosT = new javax.swing.JLabel();
        NbPersoR = new javax.swing.JLabel();
        JC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        Demarrer = new javax.swing.JButton();
        Recommencer = new javax.swing.JButton();
        Panneau = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Paramètre = new javax.swing.JMenu();
        Options = new javax.swing.JMenuItem();
        AjoutJoueur = new javax.swing.JMenuItem();
        Visualiser = new javax.swing.JMenu();
        Carte = new javax.swing.JMenuItem();
        Joueur = new javax.swing.JMenuItem();
        Test = new javax.swing.JMenu();
        Bataille_Test = new javax.swing.JMenuItem();
        Transfert_Test = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));
        jPanel2.add(NbPersosT);
        jPanel2.add(NbPersoR);
        jPanel2.add(JC);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        Edition.setColumns(20);
        Edition.setLineWrap(true);
        Edition.setRows(5);
        Edition.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Edition);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        Demarrer.setText("Demarrer");
        Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarrerActionPerformed(evt);
            }
        });
        jPanel3.add(Demarrer);

        Recommencer.setText("Recommencer");
        Recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecommencerActionPerformed(evt);
            }
        });
        jPanel3.add(Recommencer);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        Paramètre.setText("Paramètres");

        Options.setText("Options");
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });
        Paramètre.add(Options);

        AjoutJoueur.setText("AjoutJoueur");
        AjoutJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutJoueurActionPerformed(evt);
            }
        });
        Paramètre.add(AjoutJoueur);

        jMenuBar1.add(Paramètre);

        Visualiser.setText("Visualiser");

        Carte.setText("Carte");
        Carte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarteActionPerformed(evt);
            }
        });
        Visualiser.add(Carte);

        Joueur.setText("Joueur");
        Joueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoueurActionPerformed(evt);
            }
        });
        Visualiser.add(Joueur);

        jMenuBar1.add(Visualiser);

        Test.setText("Test");

        Bataille_Test.setText("Bataille");
        Bataille_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bataille_TestActionPerformed(evt);
            }
        });
        Test.add(Bataille_Test);

        Transfert_Test.setText("Transfert-test");
        Transfert_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transfert_TestActionPerformed(evt);
            }
        });
        Test.add(Transfert_Test);

        jMenuBar1.add(Test);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarteActionPerformed
        // TODO add your handling code here:
        Joueur j= this.jeu.getJoueurCourant();
        VisuPersonnagesDlg diag=new VisuPersonnagesDlg(this,true,j);
        diag.setSize(1000,600);
        diag.setVisible(true);
       
    }//GEN-LAST:event_CarteActionPerformed

    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        // TODO add your handling code here:
        InitDlg dlg = new InitDlg(this,true);
        dlg.setVisible(true);
        dlg.setSize(900,600);
        if(dlg.isOk()){
           LesJoueurs j = dlg.getLj();
        for (int i = 0; i < j.getNbJoueurs(); i++) {
            this.joueurs.ajouteJoueur(j.getJoueur(i));   
        }
        this.persos = new LesPersonnages(dlg.getNc());
        this.jeu=new Jeu(this.persos,this.joueurs,dlg.getNc());
        this.plateau=this.jeu.getPlateau();
        }
    }//GEN-LAST:event_OptionsActionPerformed
    
    private void JoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoueurActionPerformed
        // TODO add your handling code here:
        //LesJoueurs lj=new LesJoueurs();
        VisuJoueursDlg dialog= new VisuJoueursDlg(this, true,joueurs);
        dialog.setSize(1000,500);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_JoueurActionPerformed

    private void Bataille_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bataille_TestActionPerformed
        // TODO add your handling code here:
        Joueur j1=new Joueur("FanMemory1", "communs");
        j1.getPaquet().ajoutePerso(new Personnage("communs", "assault-trooper", 10));
        j1.getPaquet().ajoutePerso(new Personnage("communs", "commando", 20));
        j1.getPaquet().ajoutePerso(new Personnage("rares", "absolute-zero", 10));
        Joueur j2=new Joueur("FanMemory2", "communs");
        j2.getPaquet().ajoutePerso(new Personnage("epiques", "burnout", 20));
        j2.getPaquet().ajoutePerso(new Personnage("epiques", "funk-ops", 30));
        j2.getPaquet().ajoutePerso(new Personnage("alpins-femmes", "mogul-master", 10));
        LesJoueurs lj= new LesJoueurs();
        lj.ajouteJoueur(j1);
        lj.ajouteJoueur(j2);
        BatailleDlg diag = new BatailleDlg(this, true, lj,0);
        diag.setSize(1000,600);
        diag.setVisible(true);
    }//GEN-LAST:event_Bataille_TestActionPerformed

    private void AjoutJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutJoueurActionPerformed
        // TODO add your handling code here:
        LesPersonnages lp=new LesPersonnages();
        SaisieJoueurDlg saisie=new SaisieJoueurDlg(this, true,lp);
        saisie.setVisible(true);
        Joueur nj=saisie.getNj();
        if(saisie.isOk()){
            this.joueurs.ajouteJoueur(nj);
            //this.jeu.getLesJ().ajouteJoueur(nj);
            System.out.println("\n\n"+nj.getPseudo()+" a été ajouté manuellement et sa famille préférée est : "+nj.getFamillePref());
        }
    }//GEN-LAST:event_AjoutJoueurActionPerformed

    private void DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarrerActionPerformed
        // TODO add your handling code here:
        //test du nbre de joueurs
        if(this.joueurs.getNbJoueurs()<2)
            Edition.append("Selectionner au moins 2 joueurs\n");
        else//la partie peut commencer
        {   
            //valider/invalider les boutons
            Demarrer.setEnabled(false);
            Recommencer.setEnabled(true);
            Options.setEnabled(false);
            AjoutJoueur.setEnabled(false);
            Joueur.setEnabled(true);
            Carte.setEnabled(true);
            //Mise à jour des 3 Jlabels
            NbPersosT.setText("nombre de personnages : "+(this.plateau.getNbc()-this.plateau.getNbp()));
            NbPersoR.setText("nombre de perso restant : "+this.plateau.getNbp());
            JC.setText("c'est à "+this.jeu.getJoueurCourant().getPseudo()+" de jouer");
            // contruction dynamique du plateau 
            int l= this.plateau.getNblig();
            int c = this.plateau.getNbcol();
            Panneau.setLayout(new GridLayout(l,c));
            for (int i = 0; i < l*c; i++) {
                JButton bt = new JButton();
                bt.setName(""+i);
                bt.addActionListener(new ActionListener(){
                public void actionPerformed(ActionEvent evt){
                    boutonActionPerformed(evt);
                }
               });      
                    Panneau.add(bt);
                    bt.setIcon(new ImageIcon(getClass().getResource("/Img/Dos.PNG")));
            }       
        }
        
    }//GEN-LAST:event_DemarrerActionPerformed

    private void RecommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecommencerActionPerformed
        // TODO add your handling code here:Edition.setText("");
        Edition.setText("");
        ResetDonnees();
        NbPersosT.setText("Nombres de de personnages trouvé : ");
        NbPersoR.setText("Nombres de de personnages restant : ");
        JC.setText("Vous n'avez sélectionné aucun joueur");
        Panneau.removeAll();
        Panneau.repaint();
        Demarrer.setEnabled(true);
        Recommencer.setEnabled(true);
        Options.setEnabled(true);
        AjoutJoueur.setEnabled(true); 
        
    }//GEN-LAST:event_RecommencerActionPerformed

    private void Transfert_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transfert_TestActionPerformed
        // TODO add your handling code here:
        Joueur j1=new Joueur("FanMemory1", "communs");
        j1.getPaquet().ajoutePerso(new Personnage("communs", "assault-trooper", 10));
        j1.getPaquet().ajoutePerso(new Personnage("communs", "commando", 20));
        j1.getPaquet().ajoutePerso(new Personnage("rares", "absolute-zero", 10));
        Joueur j2=new Joueur("FanMemory2", "communs");
        j2.getPaquet().ajoutePerso(new Personnage("epiques", "burnout", 20));
        j2.getPaquet().ajoutePerso(new Personnage("epiques", "funk-ops", 30));
        j2.getPaquet().ajoutePerso(new Personnage("alpins-femmes", "mogul-master", 10));
        LesJoueurs lj= new LesJoueurs();
        lj.ajouteJoueur(j1);
        lj.ajouteJoueur(j2);
        //TransfertDlg diag = new TransfertDlg(this,true,joueurs,0);
        TransfertDlg diag = new TransfertDlg(this,true,lj,0);
        diag.setVisible(true); 
    }//GEN-LAST:event_Transfert_TestActionPerformed
                                      
    private void boutonActionPerformed(ActionEvent evt) {
            // récupérer le bouton 
            JButton bt = (JButton) evt.getSource();
            // récuperer son numéro
            int i = Integer.parseInt(bt.getName());
            
            
            // calsuler  ligne et colones correspondante 
            int lig = i/this.plateau.getNbcol();
            int col = i-lig*this.plateau.getNbcol();
            // récuperer la valeur et le personnage 
            int num = this.plateau.getCase(lig, col);
            Personnage p = this.persos.getPerso(num);
            // afficher phoo sur le bt
            p.setImgBouton(bt);
           
            // tester quelle case (1er ou 2eme)
            if (this.l1== -1 && this.c1== -1) {
                this.l1 = lig;
                this.c1=col;   
            }else if (this.l2==-1 && this.c2==-1) {
            this.l2=lig;
            this.c2=col;
            startTimer();
        }
            
     } 
    // a verifier quand on sort du if traitrer tour ect si il sont dans le if ou en dehors
    public void verifPersos(){
    //Déclarations
    Joueur jc = this.jeu.getJoueurCourant(); //Joueur Courant
    int c =  this.plateau.getNbcol();
    JButton b1 = (JButton) Panneau.getComponent(this.l1*c+this.c1);
    JButton b2 = (JButton) Panneau.getComponent(this.l2*c+this.c2);
    //Comparaison des deux cartes
    if(this.plateau.getCase(l1,c1)==this.plateau.getCase(l2, c2))
    {
        //Récuperation famille
        int n1 = this.plateau.getCase(l1, c1);
        String fam = this.persos.getPerso(n1).getFamille();
        //Appel traiterTour
        int bonus = this.jeu.TraiterTout(jc,n1);
        //traitement du bonus
        if(bonus >=0)
        {
            Edition.append("\n\n Bravo!\n"+jc.getPseudo()+" a obtenu tous les personnages de la famille : "+fam+"\n");
            TraitementBonus(bonus);
        }
        //Invalider les 2 cartes
        this.plateau.invalide(l1, c1, l2, c2);
        b1.setEnabled(false);
        b2.setEnabled(false);
        //Test fin du jeu
        if(this.plateau.jeuVide())
            resultatJeuMemory();
        
        else
            Edition.append("\n Tour avec "+jc.getPseudo()+"\n");
            NbPersosT.setText("Nombres de de personnages trouvé : "+(this.plateau.getNbc()-this.plateau.getNbp()));
            NbPersoR.setText("Nombres de de personnages restant : "+this.plateau.getNbp());
    }//Fin cartes identiques
    else
    {
        //Effacer cartes
        b1.setIcon(new ImageIcon(getClass().getResource("/Img/Dos.PNG")));
        b2.setIcon(new ImageIcon(getClass().getResource("/Img/Dos.PNG")));
        //Changer de joueur
        this.jeu.setJoueurCourant(this.jeu.getIndSuivant(this.jeu.getIndC()));
        //Mise à jour de JLabel JCLabel
        NbPersosT.setText("Nombres de de personnages trouvé :"+(this.plateau.getNbc()-this.plateau.getNbp()));
        NbPersoR.setText("Nombres de de personnages restant :"+this.plateau.getNbp());
        JC.setText("C'est à "+this.jeu.getJoueurCourant().getPseudo()+" de joueur !");
    }
    
    //Réinitialise les coordonnées l1, c1, l2 et c2 ç -1
    l1 = -1;c1 = -1;l2 = -1;c2 = -1;
    
    
}
    private void resultatJeuMemory()
    {
        Edition.append(" \n Fin du jeu "+this.joueurs);
        LesJoueurs gagants = this.joueurs.getGagnants();
        if (gagants.getNbJoueurs()==1) {
            Edition.append("Le gagant est "+gagants.getJoueur(0).getPseudo());}
         else{// plusieur gagants 
            Edition.append("Les gagants sont : \n ");
            for (int i = 0; i < gagants.getNbJoueurs(); i++) {
                Edition.append(gagants.getJoueur(i).getPseudo()+" ");
                Edition.append("\n");
            }
        }
        
    } 

  
    
    private void TraitementBonus(int b)
    {
        if (b==0) { //famille préferer
            Edition.append("c'est ma famille pref \n ");
            Edition.append(this.jeu.getJoueurCourant().getPseudo()+" a gagner");
            this.jeu.getPlateau().termineJeu();
            this.plateau = this.jeu.getPlateau();
            
            
            int nb = this.plateau.getNbc();
            for (int i = 0; i < nb*2; i++) {
                    JButton bt = (JButton) Panneau.getComponent(i);
                    bt.setEnabled(false);
            }
           
        }
        if (b == 1) {
            TransfertDlg diag = new TransfertDlg(this,true,this.joueurs,this.jeu.getIndC());
            diag.setVisible(true);
            if (diag.isOk()) {
                Edition.append(diag.getTc().toString()); // voir la diag de tr et qui récupère une instance de transfert 
                
                
            }
            Edition.append(" --> Mise a jour suite au transfert \n"+this.jeu.getJoueurCourant()+"\n");
        }
        if (b == 2) {
            BatailleDlg diag = new BatailleDlg(this,true,this.joueurs,this.jeu.getIndC());
            diag.setVisible(true);
            if (diag.isOk()) {
                Edition.append(diag.getBataille().toString());
            }else
                Edition.append(diag.getBataille().getDeroulement()+"\n");
                Edition.append("--> mise a jour suite à la bataille \n"+
                        this.jeu.getJoueurCourant()+"\n"+diag.getBataille().getAdversaire()+"\n");
        }
    
    }
    public void startTimer(){
 // définit un timer qui lance la vérification des deux persos au bout d'une seconde
    javax.swing.Timer t = new javax.swing.Timer(500, new ActionListener(){
    public void actionPerformed(ActionEvent ae){
    verifPersos(); // afaire ?
    }
    });
    t.setRepeats(false);
    t.start();
 }
 public void finJeuBoutons(){
 for(int i = 0; i < 2*this.jeu.getPlateau().getNbc(); i++)
 ((JButton)(Panneau.getComponent(i))).setEnabled(false);
 }
 public void ResetDonnees(){ //Complément bouton Recommencer
        this.persos = new LesPersonnages(4);
        this.joueurs = new LesJoueurs();
        this.l1 = -1;
        this.c1 = -1;
        this.l2 = -1;
        this.c2 = -1;
        // Réinitialise le jeu
        this.jeu = new Jeu(this.persos, this.joueurs, 4);
        this.plateau = this.jeu.getPlateau();
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeuMemory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjoutJoueur;
    private javax.swing.JMenuItem Bataille_Test;
    private javax.swing.JMenuItem Carte;
    private javax.swing.JButton Demarrer;
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel JC;
    private javax.swing.JMenuItem Joueur;
    private javax.swing.JLabel NbPersoR;
    private javax.swing.JLabel NbPersosT;
    private javax.swing.JMenuItem Options;
    private javax.swing.JPanel Panneau;
    private javax.swing.JMenu Paramètre;
    private javax.swing.JButton Recommencer;
    private javax.swing.JMenu Test;
    private javax.swing.JMenuItem Transfert_Test;
    private javax.swing.JMenu Visualiser;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
