import java.awt.Color;
import java.awt.Font;

public class CC1_mardi_0800_1000 extends javax.swing.JFrame {

    private String nomJours[];
    private String nomDays[];
    
    public CC1_mardi_0800_1000() {
        initComponents();
        initDonnees();
        for(int i=0; i<nomJours.length; i++)
            CBjours.addItem(nomJours[i]);
        // par défault la première proposition de la liste déroulante est sélectionnée
        // CBjours.setSelectedIndex(0);
    }
    
    private void initDonnees()
    {
       nomJours = new String[3];
       nomJours[0]="Lundi";
       nomJours[1]="Mardi";
       nomJours[2]="Mercredi";
       nomDays = new String[3];
       nomDays[0]="Monday";
       nomDays[1]="Tuesday";
       nomDays[2]="Wednesday";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gr_couleurs = new javax.swing.ButtonGroup();
        PanCouleurs = new javax.swing.JPanel();
        Couleur1 = new javax.swing.JButton();
        Couleur2 = new javax.swing.JButton();
        Couleur3 = new javax.swing.JButton();
        PanPolices = new javax.swing.JPanel();
        Police1 = new javax.swing.JRadioButton();
        Police2 = new javax.swing.JRadioButton();
        Police3 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        PanChoix = new javax.swing.JPanel();
        CBjours = new javax.swing.JComboBox<>();
        Beffacer = new javax.swing.JButton();
        PanResult = new javax.swing.JPanel();
        Jour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanCouleurs.setLayout(new java.awt.GridLayout(1, 3));

        Couleur1.setBackground(new java.awt.Color(255, 51, 51));
        Couleur1.setText("Rouge");
        Couleur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Couleur1ActionPerformed(evt);
            }
        });
        PanCouleurs.add(Couleur1);

        Couleur2.setBackground(new java.awt.Color(255, 255, 51));
        Couleur2.setText("Jaune");
        Couleur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Couleur2ActionPerformed(evt);
            }
        });
        PanCouleurs.add(Couleur2);

        Couleur3.setBackground(new java.awt.Color(0, 255, 0));
        Couleur3.setText("Vert");
        Couleur3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Couleur3ActionPerformed(evt);
            }
        });
        PanCouleurs.add(Couleur3);

        getContentPane().add(PanCouleurs, java.awt.BorderLayout.SOUTH);

        PanPolices.setLayout(new java.awt.GridLayout(1, 3));

        gr_couleurs.add(Police1);
        Police1.setText("Times new roman 18 pts");
        Police1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Police1ActionPerformed(evt);
            }
        });
        PanPolices.add(Police1);

        gr_couleurs.add(Police2);
        Police2.setText("Arial 24 pts");
        Police2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Police2ActionPerformed(evt);
            }
        });
        PanPolices.add(Police2);

        gr_couleurs.add(Police3);
        Police3.setText("Calibri light 36 pts");
        Police3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Police3ActionPerformed(evt);
            }
        });
        PanPolices.add(Police3);

        getContentPane().add(PanPolices, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        PanChoix.setLayout(new java.awt.GridLayout(2, 1));

        CBjours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBjoursActionPerformed(evt);
            }
        });
        PanChoix.add(CBjours);

        Beffacer.setText("Effacer le jour");
        Beffacer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Beffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeffacerActionPerformed(evt);
            }
        });
        PanChoix.add(Beffacer);

        jPanel1.add(PanChoix);

        PanResult.setLayout(new java.awt.GridLayout(1, 1));
        PanResult.add(Jour);

        jPanel1.add(PanResult);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Police1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Police1ActionPerformed
        Font f = new Font("Times new roman", 0, 18);
        Jour.setFont(f);
    }//GEN-LAST:event_Police1ActionPerformed

    private void CBjoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBjoursActionPerformed
        int ind = CBjours.getSelectedIndex();
        String d = nomDays[ind];
        Jour.setText(d);
    }//GEN-LAST:event_CBjoursActionPerformed

    private void Police2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Police2ActionPerformed
        Font f = new Font("Arial", 0, 24);
        Jour.setFont(f);
    }//GEN-LAST:event_Police2ActionPerformed

    private void Police3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Police3ActionPerformed
        Font f = new Font("Calibri light", 0, 36);
        Jour.setFont(f);
    }//GEN-LAST:event_Police3ActionPerformed

    private void Couleur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Couleur1ActionPerformed
        Color cc=Couleur1.getBackground();
        Jour.setBackground(cc);
    }//GEN-LAST:event_Couleur1ActionPerformed

    private void Couleur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Couleur2ActionPerformed
        Color cc=Couleur2.getBackground();
        Jour.setBackground(cc);
    }//GEN-LAST:event_Couleur2ActionPerformed

    private void Couleur3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Couleur3ActionPerformed
        Color cc=Couleur3.getBackground();
        Jour.setBackground(cc);
    }//GEN-LAST:event_Couleur3ActionPerformed

    private void BeffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeffacerActionPerformed
        // TODO add your handling code here:
        Font f = new Font("Times new roman", 0, 18);
        Jour.setFont(f);
        Police1.setSelected(true);
        CBjours.setSelectedItem(nomJours[0]);
        Jour.setBackground( Color.white);
        Jour.setText("");
    }//GEN-LAST:event_BeffacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CC1_mardi_0800_1000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CC1_mardi_0800_1000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CC1_mardi_0800_1000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CC1_mardi_0800_1000.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               CC1_mardi_0800_1000 cc = new CC1_mardi_0800_1000();
                cc.setVisible(true);
                cc.setLocation(200,200);
                cc.setSize(900, 400);
                cc.setTitle("Sujet TP mardi 8h00-10h00");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Beffacer;
    private javax.swing.JComboBox<String> CBjours;
    private javax.swing.JButton Couleur1;
    private javax.swing.JButton Couleur2;
    private javax.swing.JButton Couleur3;
    private javax.swing.JButton Jour;
    private javax.swing.JPanel PanChoix;
    private javax.swing.JPanel PanCouleurs;
    private javax.swing.JPanel PanPolices;
    private javax.swing.JPanel PanResult;
    private javax.swing.JRadioButton Police1;
    private javax.swing.JRadioButton Police2;
    private javax.swing.JRadioButton Police3;
    private javax.swing.ButtonGroup gr_couleurs;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
