/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOBO
 */
import java.awt.*;
public class JeuDesCouleurs extends javax.swing.JFrame {
    private Color couleur1 ;
    private Color couleur2 ;
    private int num ;


    /**
     * Creates new form JeuDesCouleurs
     */
    public JeuDesCouleurs() {
        initComponents();
        num = 1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PDroit = new javax.swing.JPanel();
        BMarron = new javax.swing.JButton();
        BJaune = new javax.swing.JButton();
        BRose = new javax.swing.JButton();
        BViolet = new javax.swing.JButton();
        PGauche = new javax.swing.JPanel();
        BBleu = new javax.swing.JButton();
        BVert = new javax.swing.JButton();
        BRouge = new javax.swing.JButton();
        BOrange = new javax.swing.JButton();
        PSud = new javax.swing.JPanel();
        LMessage = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitre.setText("Le jeu des couleurs");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(LTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(LTitre)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PDroit.setLayout(new java.awt.GridLayout(4, 1));

        BMarron.setBackground(new java.awt.Color(142, 55, 30));
        BMarron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMarronActionPerformed(evt);
            }
        });
        PDroit.add(BMarron);

        BJaune.setBackground(new java.awt.Color(255, 255, 0));
        BJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJauneActionPerformed(evt);
            }
        });
        PDroit.add(BJaune);

        BRose.setBackground(new java.awt.Color(255, 47, 181));
        BRose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRoseActionPerformed(evt);
            }
        });
        PDroit.add(BRose);

        BViolet.setBackground(new java.awt.Color(205, 121, 239));
        BViolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVioletActionPerformed(evt);
            }
        });
        PDroit.add(BViolet);

        getContentPane().add(PDroit, java.awt.BorderLayout.LINE_END);

        PGauche.setLayout(new java.awt.GridLayout(4, 1));

        BBleu.setBackground(new java.awt.Color(0, 0, 255));
        BBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBleuActionPerformed(evt);
            }
        });
        PGauche.add(BBleu);

        BVert.setBackground(new java.awt.Color(0, 255, 0));
        BVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVertActionPerformed(evt);
            }
        });
        PGauche.add(BVert);

        BRouge.setBackground(new java.awt.Color(255, 0, 0));
        BRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRougeActionPerformed(evt);
            }
        });
        PGauche.add(BRouge);

        BOrange.setBackground(new java.awt.Color(255, 118, 0));
        BOrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOrangeActionPerformed(evt);
            }
        });
        PGauche.add(BOrange);

        getContentPane().add(PGauche, java.awt.BorderLayout.LINE_START);

        LMessage.setText("Mélangez les couleurs en cliquant sur deux boutons");

        javax.swing.GroupLayout PSudLayout = new javax.swing.GroupLayout(PSud);
        PSud.setLayout(PSudLayout);
        PSudLayout.setHorizontalGroup(
            PSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
            .addGroup(PSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PSudLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LMessage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PSudLayout.setVerticalGroup(
            PSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PSudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PSudLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LMessage)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(PSud, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout PCentreLayout = new javax.swing.GroupLayout(PCentre);
        PCentre.setLayout(PCentreLayout);
        PCentreLayout.setHorizontalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        PCentreLayout.setVerticalGroup(
            PCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void melanger(){
        int r= (couleur1.getRed() + couleur2.getRed())/2 ;
        int v =(couleur1.getGreen() + couleur2.getGreen())/2;
        int b =(couleur1.getBlue() + couleur2.getBlue())/2;
        Color melange = new Color(r, v, b);
        PCentre.setBackground(melange);

    }
    
    
    private void BOrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOrangeActionPerformed
        // TODO add your handling code here:
              Color c = BOrange.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BOrangeActionPerformed

    private void BJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJauneActionPerformed
        // TODO add your handling code here:
             Color c = BJaune.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BJauneActionPerformed

    private void BBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBleuActionPerformed
        // TODO add your handling code here:
        
        Color c = BBleu.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
        
        
    }//GEN-LAST:event_BBleuActionPerformed

    private void BRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRougeActionPerformed
        // TODO add your handling code here:
              Color c = BRouge.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BRougeActionPerformed

    private void BVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVertActionPerformed
        // TODO add your handling code here:
              Color c = BVert.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BVertActionPerformed

    private void BMarronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMarronActionPerformed
        // TODO add your handling code here:
              Color c = BMarron.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BMarronActionPerformed

    private void BRoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRoseActionPerformed
        // TODO add your handling code here:
              Color c = BRose.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BRoseActionPerformed

    private void BVioletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVioletActionPerformed
        // TODO add your handling code here:
              Color c = BViolet.getBackground();
        if(this.num == 1){
            couleur1 = c;
            this.num = 2;
        }else {
            couleur2 = c;
            this.num = 1;
            melanger();
        }
    }//GEN-LAST:event_BVioletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuDesCouleurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuDesCouleurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuDesCouleurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuDesCouleurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeuDesCouleurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBleu;
    private javax.swing.JButton BJaune;
    private javax.swing.JButton BMarron;
    private javax.swing.JButton BOrange;
    private javax.swing.JButton BRose;
    private javax.swing.JButton BRouge;
    private javax.swing.JButton BVert;
    private javax.swing.JButton BViolet;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PGauche;
    private javax.swing.JPanel PSud;
    private javax.swing.JPanel PTitre;
    // End of variables declaration//GEN-END:variables
}
