/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOBO
 */
public class JeuMetier extends javax.swing.JFrame {

    /**
     * Creates new form JeuMetier
     */
    public JeuMetier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PImages = new javax.swing.JPanel();
        BISculpteur = new javax.swing.JButton();
        BIMarin = new javax.swing.JButton();
        BIPatissier = new javax.swing.JButton();
        BICoiffeur = new javax.swing.JButton();
        BIPeintre = new javax.swing.JButton();
        PMetiers = new javax.swing.JPanel();
        BPeintre = new javax.swing.JButton();
        Patissier = new javax.swing.JButton();
        BCoiffeur = new javax.swing.JButton();
        BSculpteur = new javax.swing.JButton();
        BMarin = new javax.swing.JButton();
        PSelection = new javax.swing.JPanel();
        PVide = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MonImage = new javax.swing.JButton();
        MonMetier = new javax.swing.JButton();
        PResultat = new javax.swing.JPanel();
        LResultat = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MJeu = new javax.swing.JMenu();
        MRejouer = new javax.swing.JMenuItem();
        MQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitre.setText("Le jeu des Métiers");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTitreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PTitreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LTitre)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PImages.setLayout(new java.awt.GridLayout(5, 1));

        BISculpteur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escultor.gif"))); // NOI18N
        BISculpteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BISculpteurActionPerformed(evt);
            }
        });
        PImages.add(BISculpteur);

        BIMarin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marino_piloto.gif"))); // NOI18N
        BIMarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIMarinActionPerformed(evt);
            }
        });
        PImages.add(BIMarin);

        BIPatissier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastelero.gif"))); // NOI18N
        BIPatissier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIPatissierActionPerformed(evt);
            }
        });
        PImages.add(BIPatissier);

        BICoiffeur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peluquero.gif"))); // NOI18N
        BICoiffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BICoiffeurActionPerformed(evt);
            }
        });
        PImages.add(BICoiffeur);

        BIPeintre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pintor.gif"))); // NOI18N
        BIPeintre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIPeintreActionPerformed(evt);
            }
        });
        PImages.add(BIPeintre);

        getContentPane().add(PImages, java.awt.BorderLayout.LINE_START);

        PMetiers.setLayout(new java.awt.GridLayout(5, 1));

        BPeintre.setText("Peintre");
        BPeintre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPeintreActionPerformed(evt);
            }
        });
        PMetiers.add(BPeintre);

        Patissier.setText("Patissier");
        Patissier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatissierActionPerformed(evt);
            }
        });
        PMetiers.add(Patissier);

        BCoiffeur.setText("Coiffeur");
        BCoiffeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCoiffeurActionPerformed(evt);
            }
        });
        PMetiers.add(BCoiffeur);

        BSculpteur.setText("Sculpteur");
        BSculpteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSculpteurActionPerformed(evt);
            }
        });
        PMetiers.add(BSculpteur);

        BMarin.setText("Marin");
        BMarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMarinActionPerformed(evt);
            }
        });
        PMetiers.add(BMarin);

        getContentPane().add(PMetiers, java.awt.BorderLayout.LINE_END);

        PSelection.setLayout(new java.awt.GridLayout(3, 1));

        PVide.setLayout(new java.awt.GridLayout(1, 1));
        PSelection.add(PVide);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        MonImage.setText("Image");
        jPanel2.add(MonImage);

        MonMetier.setText("Métier");
        MonMetier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonMetierActionPerformed(evt);
            }
        });
        jPanel2.add(MonMetier);

        PSelection.add(jPanel2);

        LResultat.setText("Résultat");

        javax.swing.GroupLayout PResultatLayout = new javax.swing.GroupLayout(PResultat);
        PResultat.setLayout(PResultatLayout);
        PResultatLayout.setHorizontalGroup(
            PResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PResultatLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(LResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        PResultatLayout.setVerticalGroup(
            PResultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PResultatLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(LResultat)
                .addGap(43, 43, 43))
        );

        PSelection.add(PResultat);

        getContentPane().add(PSelection, java.awt.BorderLayout.CENTER);

        MJeu.setText("Jeu");

        MRejouer.setText("Rejouer");
        MRejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRejouerActionPerformed(evt);
            }
        });
        MJeu.add(MRejouer);

        MQuitter.setText("Quitter");
        MQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MQuitterActionPerformed(evt);
            }
        });
        MJeu.add(MQuitter);

        jMenuBar1.add(MJeu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean gagne(){
        if(MonMetier.getName().equals(MonImage.getName()))
           return true;
        else
            return false;
    }
    
    private void BISculpteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BISculpteurActionPerformed
        // TODO add your handling code here:
        MonImage.setText("");
        MonImage.setName("sculpteur");
        MonImage.setIcon( BISculpteur.getIcon());
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BISculpteurActionPerformed

    private void BICoiffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BICoiffeurActionPerformed
        // TODO add your handling code here:
         MonImage.setText("");
        MonImage.setName("coiffeur");
        MonImage.setIcon( BICoiffeur.getIcon());
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BICoiffeurActionPerformed

    private void BPeintreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPeintreActionPerformed
        // TODO add your handling code here:
        MonMetier.setName("peintre");
        MonMetier.setText("Peintre");
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
            
        
    }//GEN-LAST:event_BPeintreActionPerformed

    private void PatissierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatissierActionPerformed
        // TODO add your handling code here:
        MonMetier.setName("patissier");
        MonMetier.setText("Patissier");
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
        
    }//GEN-LAST:event_PatissierActionPerformed

    private void BCoiffeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCoiffeurActionPerformed
        // TODO add your handling code here:
        MonMetier.setName("coiffeur");
        MonMetier.setText("Coiffeur");
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BCoiffeurActionPerformed

    private void BSculpteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSculpteurActionPerformed
        // TODO add your handling code here:
        MonMetier.setName("sculpteur");
        MonMetier.setText("Sculpteur");
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BSculpteurActionPerformed

    private void BMarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMarinActionPerformed
        // TODO add your handling code here:
        MonMetier.setName("marin");
        MonMetier.setText("Marin");
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BMarinActionPerformed

    private void BIMarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIMarinActionPerformed
        // TODO add your handling code here:
         MonImage.setText("");
        MonImage.setName("marin");
        MonImage.setIcon( BIMarin.getIcon());
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BIMarinActionPerformed

    private void BIPatissierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIPatissierActionPerformed
        // TODO add your handling code here:
         MonImage.setText("");
        MonImage.setName("patissier");
        MonImage.setIcon( BIPatissier.getIcon());
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BIPatissierActionPerformed

    private void BIPeintreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIPeintreActionPerformed
        // TODO add your handling code here:
         MonImage.setText("");
        MonImage.setName("peintre");
        MonImage.setIcon( BIPeintre.getIcon());
        if(gagne())
            LResultat.setText("gagné!");
        else
            LResultat.setText("encore!");
    }//GEN-LAST:event_BIPeintreActionPerformed

    private void MonMetierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonMetierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonMetierActionPerformed

    private void MRejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRejouerActionPerformed
        // TODO add your handling code here:
        MonMetier.setName("metier");
        MonMetier.setText("Métier");
        MonImage.setName("image");
        MonImage.setText("Image");
        MonImage.setIcon(null);
        LResultat.setText("Résultat");
        
    }//GEN-LAST:event_MRejouerActionPerformed

    private void MQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuMetier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuMetier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuMetier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuMetier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeuMetier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCoiffeur;
    private javax.swing.JButton BICoiffeur;
    private javax.swing.JButton BIMarin;
    private javax.swing.JButton BIPatissier;
    private javax.swing.JButton BIPeintre;
    private javax.swing.JButton BISculpteur;
    private javax.swing.JButton BMarin;
    private javax.swing.JButton BPeintre;
    private javax.swing.JButton BSculpteur;
    private javax.swing.JLabel LResultat;
    private javax.swing.JLabel LTitre;
    private javax.swing.JMenu MJeu;
    private javax.swing.JMenuItem MQuitter;
    private javax.swing.JMenuItem MRejouer;
    private javax.swing.JButton MonImage;
    private javax.swing.JButton MonMetier;
    private javax.swing.JPanel PImages;
    private javax.swing.JPanel PMetiers;
    private javax.swing.JPanel PResultat;
    private javax.swing.JPanel PSelection;
    private javax.swing.JPanel PTitre;
    private javax.swing.JPanel PVide;
    private javax.swing.JButton Patissier;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
