
import java.awt.Color;
import java.awt.Font;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ad057513
 */

public class LesBoutons extends javax.swing.JFrame {

    /**
     * Creates new form LesBboutons
     */
    public LesBoutons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PTitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PHautGauche = new javax.swing.JPanel();
        LPHautGauche = new javax.swing.JLabel();
        BRRouge = new javax.swing.JRadioButton();
        BRVert = new javax.swing.JRadioButton();
        BRBleu = new javax.swing.JRadioButton();
        BROrange = new javax.swing.JRadioButton();
        PHautDroit = new javax.swing.JPanel();
        LHautDroit = new javax.swing.JLabel();
        BCTahoma36 = new javax.swing.JCheckBox();
        BCTahoma48 = new javax.swing.JCheckBox();
        BCLucida = new javax.swing.JCheckBox();
        BCArial = new javax.swing.JCheckBox();
        PBasGauche = new javax.swing.JPanel();
        LBasGauche = new javax.swing.JLabel();
        BTRose = new javax.swing.JToggleButton();
        BTMagenta = new javax.swing.JToggleButton();
        BTJaune = new javax.swing.JToggleButton();
        BTGris = new javax.swing.JToggleButton();
        PBasDroit = new javax.swing.JPanel();
        BBasDroit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PTitre.setPreferredSize(new java.awt.Dimension(509, 50));

        LTitre.setText("Choisissez les paramètres de votre bouton !");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PTitreLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(LTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LTitre)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PCentre.setLayout(new java.awt.GridLayout(2, 2));

        PHautGauche.setLayout(new java.awt.GridLayout(5, 1));

        LPHautGauche.setText("Couleur de fond ?");
        PHautGauche.add(LPHautGauche);

        buttonGroup1.add(BRRouge);
        BRRouge.setText("Rouge");
        BRRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRRougeActionPerformed(evt);
            }
        });
        PHautGauche.add(BRRouge);

        buttonGroup1.add(BRVert);
        BRVert.setText("Vert");
        BRVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRVertActionPerformed(evt);
            }
        });
        PHautGauche.add(BRVert);

        buttonGroup1.add(BRBleu);
        BRBleu.setText("Bleu");
        BRBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRBleuActionPerformed(evt);
            }
        });
        PHautGauche.add(BRBleu);

        buttonGroup1.add(BROrange);
        BROrange.setText("Orange");
        BROrange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BROrangeActionPerformed(evt);
            }
        });
        PHautGauche.add(BROrange);

        PCentre.add(PHautGauche);

        PHautDroit.setLayout(new java.awt.GridLayout(5, 1));

        LHautDroit.setText("Fonte d'écriture ?");
        PHautDroit.add(LHautDroit);

        buttonGroup1.add(BCTahoma36);
        BCTahoma36.setText("Tahoma 36");
        BCTahoma36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCTahoma36ActionPerformed(evt);
            }
        });
        PHautDroit.add(BCTahoma36);

        buttonGroup1.add(BCTahoma48);
        BCTahoma48.setText("Tahoma 48");
        BCTahoma48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCTahoma48ActionPerformed(evt);
            }
        });
        PHautDroit.add(BCTahoma48);

        buttonGroup1.add(BCLucida);
        BCLucida.setText("Luccia Calligarphy 36");
        BCLucida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCLucidaActionPerformed(evt);
            }
        });
        PHautDroit.add(BCLucida);

        buttonGroup1.add(BCArial);
        BCArial.setText("Arial 18");
        BCArial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCArialActionPerformed(evt);
            }
        });
        PHautDroit.add(BCArial);

        PCentre.add(PHautDroit);

        PBasGauche.setLayout(new java.awt.GridLayout(5, 1));

        LBasGauche.setText("couleur d'écriture ?");
        PBasGauche.add(LBasGauche);

        BTRose.setText("Rose");
        BTRose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRoseActionPerformed(evt);
            }
        });
        PBasGauche.add(BTRose);

        BTMagenta.setText("Magenta");
        BTMagenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMagentaActionPerformed(evt);
            }
        });
        PBasGauche.add(BTMagenta);

        BTJaune.setText("Jaune");
        BTJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTJauneActionPerformed(evt);
            }
        });
        PBasGauche.add(BTJaune);

        BTGris.setText("Gris");
        BTGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGrisActionPerformed(evt);
            }
        });
        PBasGauche.add(BTGris);

        PCentre.add(PBasGauche);

        PBasDroit.setLayout(new java.awt.GridLayout(1, 1));

        BBasDroit.setText("TEXTE");
        BBasDroit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBasDroitActionPerformed(evt);
            }
        });
        PBasDroit.add(BBasDroit);

        PCentre.add(PBasDroit);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBasDroitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBasDroitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBasDroitActionPerformed

    private void BRRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRRougeActionPerformed
        // TODO add your handling code here:
        BBasDroit.setBackground(Color.red);
        
    }//GEN-LAST:event_BRRougeActionPerformed

    private void BRVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRVertActionPerformed
        // TODO add your handling code here:
         BBasDroit.setBackground(Color.green);
    }//GEN-LAST:event_BRVertActionPerformed

    private void BRBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRBleuActionPerformed
        // TODO add your handling code here:
        BBasDroit.setBackground(Color.BLUE);
    }//GEN-LAST:event_BRBleuActionPerformed

    private void BROrangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BROrangeActionPerformed
        // TODO add your handling code here:
        BBasDroit.setBackground(Color.orange);
    }//GEN-LAST:event_BROrangeActionPerformed

    private void BCTahoma36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCTahoma36ActionPerformed
        // TODO add your handling code here:
        BBasDroit.setFont(new Font("Tahoma",0,36));
    }//GEN-LAST:event_BCTahoma36ActionPerformed

    private void BCTahoma48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCTahoma48ActionPerformed
        // TODO add your handling code here:
        BBasDroit.setFont(new Font("Tahoma",0,48));
    }//GEN-LAST:event_BCTahoma48ActionPerformed

    private void BCLucidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCLucidaActionPerformed
        // TODO add your handling code here:
        BBasDroit.setFont(new Font("Lucida Calligraphy", 0, 36));

    }//GEN-LAST:event_BCLucidaActionPerformed

    private void BCArialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCArialActionPerformed
        // TODO add your handling code here:
        BBasDroit.setFont(new Font("Arial",0,18));
    }//GEN-LAST:event_BCArialActionPerformed

    private void BTRoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRoseActionPerformed
        // TODO add your handling code here:
        BBasDroit.setForeground(Color.pink);
    }//GEN-LAST:event_BTRoseActionPerformed

    private void BTMagentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMagentaActionPerformed
        // TODO add your handling code here:
        BBasDroit.setForeground(Color.magenta);
    }//GEN-LAST:event_BTMagentaActionPerformed

    private void BTJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTJauneActionPerformed
        // TODO add your handling code here:
        BBasDroit.setForeground(Color.yellow);
    }//GEN-LAST:event_BTJauneActionPerformed

    private void BTGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGrisActionPerformed
        // TODO add your handling code here:
        BBasDroit.setForeground(Color.gray);
    }//GEN-LAST:event_BTGrisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LesBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LesBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LesBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LesBoutons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LesBoutons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBasDroit;
    private javax.swing.JCheckBox BCArial;
    private javax.swing.JCheckBox BCLucida;
    private javax.swing.JCheckBox BCTahoma36;
    private javax.swing.JCheckBox BCTahoma48;
    private javax.swing.JRadioButton BRBleu;
    private javax.swing.JRadioButton BROrange;
    private javax.swing.JRadioButton BRRouge;
    private javax.swing.JRadioButton BRVert;
    private javax.swing.JToggleButton BTGris;
    private javax.swing.JToggleButton BTJaune;
    private javax.swing.JToggleButton BTMagenta;
    private javax.swing.JToggleButton BTRose;
    private javax.swing.JLabel LBasGauche;
    private javax.swing.JLabel LHautDroit;
    private javax.swing.JLabel LPHautGauche;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel PBasDroit;
    private javax.swing.JPanel PBasGauche;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PHautDroit;
    private javax.swing.JPanel PHautGauche;
    private javax.swing.JPanel PTitre;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
