/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author BOBO
 */
import java.awt.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
public class LesCouleursCm extends javax.swing.JFrame {
    
    private ArrayList<Color> lstCoulDispo;
    private ArrayList<String> lstNomCoulDispo;
    private Color tabCoulSelect[];
    private String tabNomCoulSelect[];
    private int nb;
    private final int MAX = 100;
    private Color couleurCourante;
    
    

    /**
     * Creates new form LesCouleursCm
     */
    public LesCouleursCm() {
        initComponents();
        this.lstCoulDispo = new ArrayList<>();
        this.lstNomCoulDispo = new ArrayList<>();
       this.tabCoulSelect = new Color[100];
       this.tabNomCoulSelect = new String [100];
       this.nb = 0;
       this.couleurCourante = PanCouleur.getBackground();
       initLstCoulDispo();
       initListeComboCouleurs();
       DefaultListModel mod = new DefaultListModel();
       ListeCouleur.setModel(mod);
       initListeCouleurs();
       
       
    }
    private void initListeComboCouleurs(){
        for(int i = 0; i < this.lstNomCoulDispo.size(); i++)
            ListeComboCouleur.addItem(lstNomCoulDispo.get(i));
        
    }
    private void initLstCoulDispo(){
        Color c;
        c = new Color(0,127,155);
        lstCoulDispo.add(c);
        lstNomCoulDispo.add("Bleu Azur");
       
    }
    private void initListeCouleurs(){
        DefaultListModel mod = (DefaultListModel) ListeCouleur.getModel();
        for(int i = 0; i < this.lstNomCoulDispo.size(); i++)
            mod.addElement(this.lstNomCoulDispo.get(i));
        
    }
    private void afficherInformations(){
        Edition.setText("");
        for(int i = 0; i <nb; i++)
            Edition.append("\n" + tabNomCoulSelect[i]);
        Edition.append("\nCouleur actuelle" + couleurCourante.getRed()+""+couleurCourante.getGreen()+""+""+couleurCourante.getBlue());
        
    }
    public void colorierPanneau(){
        int vert,bleu,rouge;
        vert = 0; rouge = 0; bleu = 0;
        if(this.nb != 0){
            for(int i = 0; i < this.nb; i++){
                vert += tabCoulSelect[i].getGreen();
                rouge += tabCoulSelect[i].getRed();
                bleu += tabCoulSelect[i].getBlue();          
            }
            vert = vert / this.nb;
            rouge = rouge / this.nb;
            bleu = bleu / this.nb;
            System.out.println(rouge + ""+vert +""+""+bleu);
            couleurCourante = new Color(rouge, vert,bleu);
            PanCouleur.setBackground(couleurCourante);
            
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupeCouleurs = new javax.swing.ButtonGroup();
        PTitre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PCentreHaut = new javax.swing.JPanel();
        PRadio = new javax.swing.JPanel();
        BRRouge = new javax.swing.JRadioButton();
        BRVert = new javax.swing.JRadioButton();
        BRBleu = new javax.swing.JRadioButton();
        PListeCombo = new javax.swing.JPanel();
        LMessage = new javax.swing.JLabel();
        ListeComboCouleur = new javax.swing.JComboBox<>();
        PComboCouleur = new javax.swing.JPanel();
        BAjouter = new javax.swing.JButton();
        PVide = new javax.swing.JPanel();
        PanList = new javax.swing.JPanel();
        LListeCoul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeCouleur = new javax.swing.JList<>();
        PCentreBas = new javax.swing.JPanel();
        PanCouleur = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        PBas = new javax.swing.JPanel();
        BReset = new javax.swing.JButton();
        BFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PTitre.setPreferredSize(new java.awt.Dimension(625, 50));

        jLabel1.setText("Mélange les couleurs !");

        javax.swing.GroupLayout PTitreLayout = new javax.swing.GroupLayout(PTitre);
        PTitre.setLayout(PTitreLayout);
        PTitreLayout.setHorizontalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        PTitreLayout.setVerticalGroup(
            PTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PTitreLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(PTitre, java.awt.BorderLayout.PAGE_START);

        PCentre.setLayout(new java.awt.GridLayout(2, 1));

        PCentreHaut.setLayout(new java.awt.GridLayout(1, 3));

        PRadio.setLayout(new java.awt.GridLayout(3, 1));

        GroupeCouleurs.add(BRRouge);
        BRRouge.setText("Rouge");
        BRRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRRougeActionPerformed(evt);
            }
        });
        PRadio.add(BRRouge);

        GroupeCouleurs.add(BRVert);
        BRVert.setText("Vert");
        BRVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRVertActionPerformed(evt);
            }
        });
        PRadio.add(BRVert);

        GroupeCouleurs.add(BRBleu);
        BRBleu.setText("Bleu");
        BRBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRBleuActionPerformed(evt);
            }
        });
        PRadio.add(BRBleu);

        PCentreHaut.add(PRadio);

        PListeCombo.setLayout(new java.awt.GridLayout(5, 1));

        LMessage.setText("Choisissez une couleur à ajouter !");
        PListeCombo.add(LMessage);

        ListeComboCouleur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListeComboCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeComboCouleurActionPerformed(evt);
            }
        });
        PListeCombo.add(ListeComboCouleur);

        PComboCouleur.setLayout(new java.awt.GridLayout(1, 1));
        PListeCombo.add(PComboCouleur);

        BAjouter.setText("Ajouter");
        BAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjouterActionPerformed(evt);
            }
        });
        PListeCombo.add(BAjouter);

        PVide.setLayout(new java.awt.GridLayout(1, 1));
        PListeCombo.add(PVide);

        PCentreHaut.add(PListeCombo);

        PanList.setLayout(new java.awt.BorderLayout());

        LListeCoul.setText("Choisissez une couleur ");
        LListeCoul.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PanList.add(LListeCoul, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(48, 180));

        ListeCouleur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListeCouleur);

        PanList.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        PCentreHaut.add(PanList);

        PCentre.add(PCentreHaut);

        PCentreBas.setLayout(new java.awt.GridLayout(1, 2));

        PanCouleur.setLayout(new java.awt.GridLayout(1, 1));
        PCentreBas.add(PanCouleur);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        PCentreBas.add(jScrollPane2);

        PCentre.add(PCentreBas);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        PBas.setPreferredSize(new java.awt.Dimension(625, 50));

        BReset.setText("Recommencer");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        PBas.add(BReset);

        BFermer.setText("Fermer");
        PBas.add(BFermer);

        getContentPane().add(PBas, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRRougeActionPerformed
        // TODO add your handling code here:
        this.tabCoulSelect[nb] = Color.red;
        this.tabNomCoulSelect[nb] = "Rouge";
        this.nb ++;
        colorierPanneau();
        afficherInformations();
        
    }//GEN-LAST:event_BRRougeActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        GroupeCouleurs.clearSelection();
        this.nb = 0;
        Edition.setText("");
        PanCouleur.setBackground(PVide.getBackground());
    }//GEN-LAST:event_BResetActionPerformed

    private void BRVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRVertActionPerformed
        // TODO add your handling code here:
         this.tabCoulSelect[nb] = Color.green;
        this.tabNomCoulSelect[nb] = "Vert";
        this.nb ++;
        colorierPanneau();
        afficherInformations();
    }//GEN-LAST:event_BRVertActionPerformed

    private void BRBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRBleuActionPerformed
        // TODO add your handling code here:
         this.tabCoulSelect[nb] = Color.blue;
        this.tabNomCoulSelect[nb] = "Bleu";
        this.nb ++;
        colorierPanneau();
        afficherInformations();
    }//GEN-LAST:event_BRBleuActionPerformed

    private void ListeComboCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeComboCouleurActionPerformed
        // TODO add your handling code here:
        int ind = ListeComboCouleur.getSelectedIndex();
        if(ind != -1)
            PComboCouleur.setBackground(this.lstCoulDispo.get(ind));
    }//GEN-LAST:event_ListeComboCouleurActionPerformed

    private void BAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjouterActionPerformed
        // TODO add your handling code here:
        int ind = ListeComboCouleur.getSelectedIndex();
        if(ind != -1){
            this.tabCoulSelect[nb] = this.lstCoulDispo.get(ind);
            this.tabNomCoulSelect[nb] = this.lstNomCoulDispo.get(ind);
            this.nb ++;
            colorierPanneau();
            afficherInformations();
        }
    }//GEN-LAST:event_BAjouterActionPerformed

    private void ListeCouleursMouseClicked(java.awt.event.MouseEvent evt){
       int ind = ListeCouleur.getSelectedIndex();
       tabCoulSelect[this.nb] = lstCoulDispo.get(ind);
       tabNomCoulSelect[this.nb] = lstNomCoulDispo.get(ind);
       this.nb ++;
       colorierPanneau();
       afficherInformations();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LesCouleursCm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LesCouleursCm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LesCouleursCm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LesCouleursCm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LesCouleursCm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAjouter;
    private javax.swing.JButton BFermer;
    private javax.swing.JRadioButton BRBleu;
    private javax.swing.JRadioButton BRRouge;
    private javax.swing.JRadioButton BRVert;
    private javax.swing.JButton BReset;
    private javax.swing.JTextArea Edition;
    private javax.swing.ButtonGroup GroupeCouleurs;
    private javax.swing.JLabel LListeCoul;
    private javax.swing.JLabel LMessage;
    private javax.swing.JComboBox<String> ListeComboCouleur;
    private javax.swing.JList<String> ListeCouleur;
    private javax.swing.JPanel PBas;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PCentreBas;
    private javax.swing.JPanel PCentreHaut;
    private javax.swing.JPanel PComboCouleur;
    private javax.swing.JPanel PListeCombo;
    private javax.swing.JPanel PRadio;
    private javax.swing.JPanel PTitre;
    private javax.swing.JPanel PVide;
    private javax.swing.JPanel PanCouleur;
    private javax.swing.JPanel PanList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
